<?php
		//Generated by ManagerGenerator::generate() on 06/06/2017 11:24:56
class ManagerUnite_joueur {
	/** Instance de la classe (managerUnite_joueur) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Unite_joueur) */
	private static $_aListeUnite_joueur = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Unite_joueur11]*/	/*[/TAG-Unite_joueur11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct() on 06/06/2017 11:24:56
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct() on 06/06/2017 11:24:56
		// TODO ??
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance() on 06/06/2017 11:24:56
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone() on 06/06/2017 11:24:56
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion() on 06/06/2017 11:24:56
		self::$_oConnexion = database::getInstance();// pas besoin de parametrer, un manager arrive apres la conf
	}

	public function __set($name,$id) {
		//Generated by ManagerGenerator::generateSet() on 06/06/2017 11:24:56
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet() on 06/06/2017 11:24:56
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($id=-1) {
		//Generated by ManagerGenerator::generateGetById() on 06/06/2017 11:24:56
		if ($id == -1) {
			//Toute les informations
			return FactoryUnite_joueur::getFromTableUnite_joueur($id);
		} else {
			//Verification si l'objet n'est pas en memoire
			if ($id > 0 && !array_key_exists($id,self::$_aListeUnite_joueur)) {
				self::$_aListeUnite_joueur[$id] = FactoryUnite_joueur::getFromTableUnite_joueur($id);
			}
		}
		return self::$_aListeUnite_joueur[$id];
	}

	public function getFromExtTableMembre($membre=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getMembre() == $membre) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableMembre($membre);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromMembre($idmembre) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableEquipementarmegauche($equipementarmegauche=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getEquipementarmegauche() == $equipementarmegauche) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableEquipementarmegauche($equipementarmegauche);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromEquipementarmegauche($idequipementarmegauche) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableEquipementarmedroite($equipementarmedroite=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getEquipementarmedroite() == $equipementarmedroite) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableEquipementarmedroite($equipementarmedroite);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromEquipementarmedroite($idequipementarmedroite) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableEquipementarmure($equipementarmure=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getEquipementarmure() == $equipementarmure) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableEquipementarmure($equipementarmure);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromEquipementarmure($idequipementarmure) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableEquipementcoiffe($equipementcoiffe=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getEquipementcoiffe() == $equipementcoiffe) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableEquipementcoiffe($equipementcoiffe);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromEquipementcoiffe($idequipementcoiffe) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableEquipementetendart($equipementetendart=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getEquipementetendart() == $equipementetendart) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableEquipementetendart($equipementetendart);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromEquipementetendart($idequipementetendart) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableTile($tile=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getTile() == $tile) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableTile($tile);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromTile($idtile) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableCamp($camp=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getCamp() == $camp) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableCamp($camp);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromCamp($idcamp) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function getFromExtTableDimension($dimension=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 06/06/2017 11:24:56
		//Verification en memoire
		foreach (self::$_aListeUnite_joueur AS $oUnite_joueur) {
			if ($oUnite_joueur->getDimension() == $dimension) {
				return $oUnite_joueur;
			}
		}
		// Appel de la methode de la Fabrique
		$oUnite_joueur = FactoryUnite_joueur::getFromExtTableDimension($dimension);
		// Memorisation pour plus tard
		self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
		// Renvoie de la donnee
		return $oUnite_joueur;
	}

	public function deleteCompositeLinksFromDimension($iddimension) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 06/06/2017 11:24:56
		//TODO
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete() on 06/06/2017 11:24:56
		// Verification
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		// si ce n'est pas une instance de la classe, on la cree
		if (! $object instanceof Unite_joueur) {
			$oUnite_joueur = new Unite_joueur($object['id'],$object['membre'],$object['nom'],$object['description'],$object['def_av'],$object['def_ar'],$object['def_g'],$object['def_d'],$object['mouvement'],$object['experience'],$object['equipementarmegauche'],$object['equipementarmedroite'],$object['equipementarmure'],$object['equipementcoiffe'],$object['equipementetendart'],$object['toucher'],$object['initiative'],$object['sauvegarde'],$object['endurance'],$object['cac'],$object['fo'],$object['attaque'],$object['intell'],$object['ty'],$object['capacite'],$object['pilote'],$object['co_pilote'],$object['cout'],$object['date_creation'],$object['tile'],$object['camp'],$object['chemin'],$object['dimension'],$object['aattaquecetour'],$object['sestdeplacecetour'],$object['achargecetour'],$object['pdv'],$object['ingame']);
		} else {
			$oUnite_joueur = $object;
		}
		// Appel de la methode delete de l'objet
		// Tout se passe dans une transaction ouverte plus haut
			// Execution de la requete
		if (database::getInstance()->executeRequete($oUnite_joueur->delete())) {
			// Requete OK
			unset(self::$_aListeUnite_joueur[$oUnite_joueur->getId()]);
			return true;
		} else {
			// Requete NOK lancement d'une exception PDO
			throw new PDOException('Erreur sur delete (Unite_joueur)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate() on 06/06/2017 11:24:56
		// Verification
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		// si ce n'est pas une instance de la classe, on la cree
		if (! $object instanceof Unite_joueur) {
			$oUnite_joueur = new Unite_joueur($object['id'],$object['membre'],$object['nom'],$object['description'],$object['def_av'],$object['def_ar'],$object['def_g'],$object['def_d'],$object['mouvement'],$object['experience'],$object['equipementarmegauche'],$object['equipementarmedroite'],$object['equipementarmure'],$object['equipementcoiffe'],$object['equipementetendart'],$object['toucher'],$object['initiative'],$object['sauvegarde'],$object['endurance'],$object['cac'],$object['fo'],$object['attaque'],$object['intell'],$object['ty'],$object['capacite'],$object['pilote'],$object['co_pilote'],$object['cout'],$object['date_creation'],$object['tile'],$object['camp'],$object['chemin'],$object['dimension'],$object['aattaquecetour'],$object['sestdeplacecetour'],$object['achargecetour'],$object['pdv'],$object['ingame']);
		} else {
			$oUnite_joueur = $object;
		}
		// Maintenant on compare avec celle en session
		if (!empty($_SESSION['unite_joueur']) && sizeof($_SESSION['unite_joueur']->compareTo($oUnite_joueur)) > 0) {
			$_SESSION['unite_joueur'] = $oUnite_joueur;
		}
		if ($oUnite_joueur->getId() == 0) {
			//Go TO SAVE
			self::save($oUnite_joueur);
		} else {
			// on update car les objets sont different
			if (database::getInstance()->executeRequete($oUnite_joueur->update()) === true) {
				//maj id dans la liste
				self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
				return true;
			} else {
				return false;
			}
		}
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave() on 06/06/2017 11:24:56
		// Verification
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		// si ce n'est pas une instance de la classe, on la cree
		if (! $object instanceof Unite_joueur) {
			$oUnite_joueur = new Unite_joueur($object['id'],$object['membre'],$object['nom'],$object['description'],$object['def_av'],$object['def_ar'],$object['def_g'],$object['def_d'],$object['mouvement'],$object['experience'],$object['equipementarmegauche'],$object['equipementarmedroite'],$object['equipementarmure'],$object['equipementcoiffe'],$object['equipementetendart'],$object['toucher'],$object['initiative'],$object['sauvegarde'],$object['endurance'],$object['cac'],$object['fo'],$object['attaque'],$object['intell'],$object['ty'],$object['capacite'],$object['pilote'],$object['co_pilote'],$object['cout'],$object['date_creation'],$object['tile'],$object['camp'],$object['chemin'],$object['dimension'],$object['aattaquecetour'],$object['sestdeplacecetour'],$object['achargecetour'],$object['pdv'],$object['ingame']);
		} else {
			$oUnite_joueur = $object;
		}
		if ($oUnite_joueur->getId() > 0) {
			//Go TO UPDATE
			self::update($oUnite_joueur);
		} else {
			// Appel de la methode update de l'objet
			if (database::getInstance()->executeRequete($oUnite_joueur->save()) === true) {
				//maj id dans la liste
				self::$_aListeUnite_joueur[$oUnite_joueur->getId()] = $oUnite_joueur;
				return true;
			} else {
				return false;
			}
		}
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy() on 06/06/2017 11:24:56
		// creation d'un objet de base de la classe
		$object = new Unite_joueur();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeUnite_joueur); $i++) {
			$object = $this -> _aListeUnite_joueur[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Unite_joueur de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getUnite_joueurVide() {
		//Generated by ManagerGenerator::generateGetObjetVide() on 06/06/2017 11:24:56
		return new Unite_joueur();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Unite_joueur21]*/
	

	public function attaque($attaquant,$defenseur) {
		//20170316, CBA, mise en commun des code Unite/Unite_Joueur
		ManagerUnite::getInstance()->attaque($attaquant,$defenseur);
		
// 		if (empty($attaquant)) {
// 			alerte("ERREUR, Impossible, il faut au moins l'attaquant.");
// 			return;
// 		}
		
// 		if (!is_null($attaquant) && $attaquant->getIngame() == 0) {
// 			alerte("ERREUR, Impossible, l'attaquant est hors jeu.");
// 			return;
// 		}
		
// 		if (!is_null($defenseur) && $defenseur->getIngame() == 0) {
// 			alerte("ERREUR, Impossible, le d&eacute;fenseur est hors jeu.");
// 			return;
// 		}

// 		if ($attaquant instanceof Unite_joueur) {
// 			//ce test est necessaire car au cours d'un combat,
// 			//une arme peu ne plus etre disponible
// 			//canAttack retourne un tableau:
// 			//[0]=> 0/1 impossible/possible
// 			//[1]=> instance de ActionAttaque
// 			$attaque = $attaquant->canAttack();
			
// 			if ($attaque[0] == 0) {
// 				alerte("Atttaque Impossible, pas d'arme");
// 				return;
// 			} else {
// 				// A partir d'ici, nous savons si l'unite peut ou non attaquer
				
// 				// L'unite n'est pas sur une carte ==> impossible
// 				$oCaseAttaquant = ManagerTile::getInstance()->getById($attaquant->getTile());
// // 				if (empty($oCaseAttaquant)) {
// //    					$oCaseAttaquant = FactoryTile::getFromExtTableUnite($attaquant->getId());
// //  					if (empty($oCaseAttaquant)) {
// // 						alerte("L'unite attaquante n'est pas sur une table de jeu");
// // 						return;
// //    					}
// // 				}
				
// 				if (!is_null($defenseur)) {
// 					//Attaque ciblee sur une unite/equipement
// 					$listeCasesAAttaquer[] = ManagerTile::getInstance()->getById($defenseur->getTile());
// 				} else {
//  					// 2) Chargement des unites presentes dans le rayon d'action de l'arme
// // 					$rayon = ($attaquant->getIdarmegauche() > 0) ? $attaquant->getArmegauche()->getPorteTotale() : ($attaquant->getIdarmedroit() > 0) ? $attaquant->getArmedroit()->getPorteTotale() : 0 ;

// // 					/* la liste des cases dans le rayon de l'arme */
// // 					$xMin = $oCaseAttaquant->getX() - intval(max($rayon));
// // 					if ($xMin < 0) {
// // 						$xMin = 0;
// // 					}
// // 					$xMax = $oCaseAttaquant->getX() + intval(max($rayon));
// // 					$yMin = $oCaseAttaquant->getY() - intval(max($rayon));
// // 					if ($yMin < 0) {
// // 						$yMin = 0;
// // 					}
// // 					$yMax = $oCaseAttaquant->getY() + intval(max($rayon));
// // 					$listeCasesAAttaquer = FactoryTile::getBusyCasesCarteFromRange($oCaseAttaquant->getIdcarte(),$xMin,$xMax,$yMin,$yMax);
// 					$listeCasesAAttaquer = $this->isThereEnnemies($oCaseAttaquant,$attaquant->getPorteeArme());
// 				}

// 				// Maintenant il faut parcourir la liste des unites presentes et lancer les attaques
// 				foreach ($listeCasesAAttaquer AS $oCase) {
// 					$resultCompare = $oCase->compareTo($oCaseAttaquant);
// 					if (!empty($resultCompare)) {
// 						//La case n'est pas la mienne
						
// 						//L'unite est-elle bloquee au corps-a-corps?
// 						if (ManagerUnite::getInstance()->fightLockOn($_SESSION['uniteJoueur'])) {
// 							debug("Unit&eacute; ".$attaquant->getNom()." bloqu&eacute; dans un corps-&agrave;-corps, ne peut pas tirer.",true);
// 							//ici il faut maintenant passer a une attaque corps-a-corps
// 							$attaque[1] = new Actionattaque("Arme Corps a Corps");
// 						}
						
// 						if (!empty($attaque[1])) {
// 							//L'objet ActionAttaque existe bien
// 							debug("Attaque case (".$oCase->getId().", x".$oCase->getX()."/y".$oCase->getY().")",true);
							
// 							//si le rayon d'action de l'arme et 1 => corps-a-corps
// 							//sinon tir
// 							if (ManagerUnite::getInstance()->fightLockOn($_SESSION['uniteJoueur']) || max($attaquant->getPorteeArme()) == 1) {
// 								//corps-a-corps
// 								if (ManagerTile::getInstance()->distanceEntre($oCaseAttaquant, $oCase) == 1) {
// 									debug("Corps-a-corps",true);
// 									if ( $attaque[1]->attaque($attaquant,$defenseur) === false) {
// 										return;
// 									}
									
// 									//resolution des blessures
// 									if ($attaque[1]->getBlessures() > 0) {
// 										debug("Blessure Corps-a-corps: ".$attaque[1]->getBlessures(),true);
// 										debug("assignation des blessures Corps-a-corps",true);
// 										$defenseur->encaisse($attaque[1]->getBlessures());
// 										if ($defenseur->getPdv() <= 0) {
// 											debug("Unit&eacute; d&eacute;truite.",true);
// 											//on la sort du terrain de jeu
// 											self::setUnitOutOfGame($defenseur);
// 											debug("Unit&eacute; retir&eacute;e de la partie.",true);
// 										}
// 									}
// 									//riposte du defenseur si elle est possible
// 									//Test de commandement ssi pas attaque le tour d'avant
// 									//debug($defenseur->getIngame().'/'.$defenseur->getAAttaqueCeTour(),true);
// 									if ($defenseur->getIngame() == 1 && $defenseur->getAAttaqueCeTour() == 0) {
// 										$valeurDes = lanceDes2(array('2D6'));
// 										if ($valeurDes[0] < $defenseur->getInitiative()) {
// 											debug("test reussi: ".$valeurDes[0]." < ".$defenseur->getInitiative(),true);
// 											$riposte = $defenseur->canAttack();
// 											if (!empty($riposte[1])) {
// 												//L'objet ActionAttaque existe bien
// 												debug("riposte",true);
// 												$riposte[1]->attaque($defenseur,$attaquant);
// 												if ($riposte[1]->getBlessures() > 0) {
// 													debug("Blessure riposte Corps-a-corps: ".$riposte[1]->getBlessures(),true);
// 													debug("assignation des blessures riposte Corps-a-corps",true);
// 													$attaquant->encaisse($riposte[1]->getBlessures());
// 													if ($attaquant->getPdv() <= 0) {
// 														debug("Unit&eacute; d&eacute;truite.",true);
// 														//on la sort du terrain de jeu
// 														self::setUnitOutOfGame($attaquant);
// 														debug("Unit&eacute; retir&eacute;e de la partie.",true);
// 													}
// 												}
// 											}
// 										} else {
// 											debug("test KO: ".$valeurDes[0]." > ".$defenseur->getInitiative(),true);
// 										}
// 									}
// 								}
// 							} else {
// 								//tir
// // 								if ($oCaseAttaquant->distanceAvec($oCase) <= floor(max($rayon) / 2)) {
// 								if (ManagerTile::getInstance()->distanceEntre($oCaseAttaquant, $oCase) <= floor(max($attaquant->getPorteeArme()) / 2)) {
// 									//Tir rapide possible == 2 tirs sur rayon / 2
// 									//test car il faut l'implementer dans la base
// 									debug("Distance == 1/2 R => Tir rapide attaque 1",true);
// 									$attaque[1]->attaque($attaquant,$defenseur);
// 									//resolution des blessures
// 									if ($attaque[1]->getBlessures() > 0) {
// 										debug("premieres blessure du tir rapide 1: ".$attaque[1]->getBlessures(),true);
// 										debug("assignation des blessures du tir rapide 1",true);
// 										$defenseur->encaisse($attaque[1]->getBlessures());
// 										if ($defenseur->getPdv() > 0) {
// 											debug("Distance == 1/2 R => Tir rapide attaque 2",true);
// 											$attaque[1]->attaque($attaquant,$defenseur);
// 											if ($attaque[1]->getBlessures() > 0) {
// 												debug("Blessure(s) du tir rapide 2: ".$attaque[1]->getBlessures(),true);
// 												debug("Assignation des blessures du tir rapide 2",true);
// 												$defenseur->encaisse($attaque[1]->getBlessures());
// 												if ($defenseur->getPdv() < 0) {
// 													debug("Unit&eacute; d&eacute;truite.",true);
// 													//on la sort du terrain de jeu
// 													self::setUnitOutOfGame($defenseur);
// 													debug("Unit&eacute; retir&eacute;e de la partie.",true);
// 												}
// 											} else {
// 												debug("Pas de blessures",true);
// 											}
// 										} else {
// 											debug("Unit&eacute; d&eacute;truite.",true);
// 											//on la sort du terrain de jeu
// 											self::setUnitOutOfGame($defenseur);
// 											debug("Unit&eacute; retir&eacute;e de la partie.",true);
// 										}
// 									} else {
// 										debug("Pas de blessures",true);
// 									}
// 								} else {//FIN TIR RAPIDE
// 									//tir classique == 1 tir
// 									debug("Tir Normal",true);
// 									$attaque[1]->attaque($attaquant,$defenseur);
// 								}
// 								//riposte du defenseur si elle est possible
// 								//Test de commandement ssi pas attaque le tour d'avant
// 								if ($defenseur->getIngame() == 1 && $defenseur->getAAttaqueCeTour() == 0) {
// 									$valeurDes = lanceDes2(array('2D6'));
// 									if ($valeurDes[0] < $defenseur->getInitiative()) {
// 										debug("test reussi: ".$valeurDes[0]." < ".$defenseur->getInitiative(),true);
// 									} else {
// 										debug("test KO: ".$valeurDes[0]." > ".$defenseur->getInitiative(),true);
// 									}
// 								}
// 							}
// 						}
// 					} //FIN IF "CE N'EST PAS MA CASE"
// 				} //FIN FOREACH
// 			} // FIN ELSE PEUT ATTAQUER
// 		}
// 		if ($attaquant instanceof Equipement_joueur) {
// 			/* C'est un equipement que a l'action d'attaque (Ex: mine) */
// 			ManagerEquipement_joueur::getInstance()->attaque($attaquant,$defenseur);
// 		} else if ($attaquant instanceof Equipement) {
// 			//ne devrait pas etre atteint
// 			ManagerEquipement::getInstance()->attaque($attaquant,$defenseur);
// 		}
	}
	
	/**
	 * Methode de recherche d'ennemis dans le rayon de l'arme de l'unite
	 * @param Tile $oCaseAttaquant
	 * @param int $idCarte
	 * @param array $rayon
	 * @return array <multitype:Tile, multitype:Tile >
	 */
	public function isThereEnnemies($oCaseAttaquant,$rayon) {
		// la liste des cases dans le rayon de l'arme
		$xMin = $oCaseAttaquant->getX() - intval(max($rayon));
		if ($xMin < 0) {
			$xMin = 0;
		}
		$xMax = $oCaseAttaquant->getX() + intval(max($rayon));
		$yMin = $oCaseAttaquant->getY() - intval(max($rayon));
		if ($yMin < 0) {
			$yMin = 0;
		}
		$yMax = $oCaseAttaquant->getY() + intval(max($rayon));
	
		return FactoryTile::getBusyCasesCarteFromRange($oCaseAttaquant->getCarte(),$xMin,$xMax,$yMin,$yMax);
	}
	
	public function setUnitOutOfGame($oUnite) {
		if ($oUnite instanceof Unite && !$oUnite instanceof Unite_joueur) {
			ManagerUnite::getInstance()->setUnitOutOfGame($oUnite);
		} else {
			try {
				$requete = "UPDATE unite_joueur SET tile = 0,ingame = 0 ";
				$requete .= "WHERE id = :id";
				database::getInstance()->prepareRequete($requete);
				database::getInstance()->bind(array('id' => $oUnite->getId()));
				database::getInstance()->executeRequete();
				//meme chose sur la case
				$requete = "UPDATE tile SET unite_joueur = 0 ";
				$requete .= "WHERE unite_joueur = :idunitejoueur";
				database::getInstance()->prepareRequete($requete);
				database::getInstance()->bind(array('idunitejoueur' => $oUnite->getId()));
				return database::getInstance()->executeRequete();
			} catch (PDOException $pdoE) {
				throw new PDOException('Erreur sur setUnitOutOfGame: '.$pdoE->getMessage());
			}
		}
	}
	
	/**
	 * Methode de remise en jeu d'une Unite
	 * @param object $oUnite
	 * @throws PDOException
	 */
	public function setUnitInGame($oUnite,$idTile) {
// 		if (!($oUnite instanceof Unite)) {
// // 			ManagerUnite_joueur::getInstance()->setUnitInGame($oUnite);
// 		} else {
			$retour = true;
			$requete = "UPDATE unite_joueur SET tile = :tile, ingame = 1 ";
			$requete .= "WHERE id =  :id";
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('id' => $oUnite->getId(),'tile' => $idTile));
			//UPDATE retourne le nombre de ligne modifiees
			$retour = database::getInstance()->executeRequete();
			//meme chose sur la case
			$requete = "UPDATE tile SET unite_joueur = :unite_joueur ";
			$requete .= "WHERE id = :id";
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('id' => $idTile,'unite_joueur' => $oUnite->getId()));
				//UPDATE retourne le nombre de ligne modifiees
// 				return database::getInstance()->executeRequete();
			$retour = database::getInstance()->executeRequete();
// 		}
		return $retour;
	}
	
	public function setUnitsOutOfGame($idCarte) {
		$requete = "UPDATE unite_joueur SET idtile = 0,ingame = 0 ";
		$requete .= "WHERE idtile IN (SELECT id FROM tile WHERE idcarte = :idcarte)";
		database::getInstance()->prepareRequete($requete);
		database::getInstance()->bind(array('idcarte' => $idcarte));		
		return database::getInstance()->executeRequete($requete);
	}
	
	
	/**
	 * Methode pour sortir toutes les Unites du plateau de jeu, a partir de l'identifiant du plateau
	 * @param int $idCarte
	 * @throws PDOException
	 * @return boolean
	 */
	public function setUnitsOutOfGameFromMapId($idCarte) {
		$requete = "UPDATE unite_joueur SET tile = 0,ingame = 0 ";
		$requete .= "WHERE tile IN (SELECT id FROM tile WHERE carte = :carte)";
		database::getInstance()->prepareRequete($requete);
		database::getInstance()->bind(array('carte' => $idCarte));
		if (database::getInstance()->executeRequete()) {
			//meme chose sur la case
			$requete = "UPDATE tile SET idunite_joueur = 0 ";
			$requete .= "WHERE carte = :carte ";
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('carte' => $idCarte));
			return database::getInstance()->executeRequete();	
		} else {
			throw new PDOException('Erreur sur setUnitsOutOfGameFromMapId (Unite_Joueur)');
		}
	}
	
	/**
	 * Retourne la liste des unites sur une case (quelle que soit la carte)
	 * @return array <multitype:Unite , unknown>
	 */
	public function getUnitOnTileList() {
		//ATTENTION IL FAUDRA MODIFIER LE FACTORYGENERATOR
		return FactoryUnite_joueur::getFromExtTableTile();
	}
	
	public function getAllUnits() {
		if (!empty(self::$_aListeUnite_joueur)) {
			return self::$_aListeUnite_joueur;
		}
	}
	
	public function setUnitOutOfCase($oUnite) {
		if ($oUnite instanceof Unite && !$oUnite instanceof Unite_joueur) {
			ManagerUnite::getInstance()->setUnitOutOfCase($oUnite);
		} else {
			$requete = "UPDATE unite_joueur SET idtile = 0 ";
			$requete .= "WHERE id = :id";
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('id' => $oUnite->getId()));
			if (database::getInstance()->executeRequete($requete)) {
				//meme chose sur la case
				$requete = "UPDATE tile SET idunitejoueur = 0 ";
				$requete .= "WHERE idunitejoueur = :idunitejoueur";
				database::getInstance()->prepareRequete($requete);
				database::getInstance()->bind(array('idunitejoueur' => $oUnite->getId()));
				return database::getInstance()->executeRequete($requete);
			} else {
				throw new PDOException('Erreur sur setUnitsOutOfCase (Unite_joueur)');
			}
		}
	}
	
	public function getListeUniteParJoueur() {
		return FactoryUnite_joueur::getListeUnitesParJoueur();		
	}

	public function switchWeapon($idUniteJoueur,$idEquipementJoueur) {
		//Creation de l'objet Unite
		$oUniteJoueur = self::getById(intval($idUniteJoueur));
		//Creation de l'objet Equipement
		$oEquipementJoueur = ManagerEquipement_joueur::getInstance()->getById(intval($idEquipementJoueur));
		//mise a jour de la nouvelle arme
		if ($oEquipementJoueur->getDeux_mains() == 1) {
			$oUniteJoueur->setEquipementarmedroite(intval($idEquipementJoueur));
			$oUniteJoueur->setEquipementarmegauche(intval($idEquipementJoueur));
		} else {
			$oUniteJoueur->setEquipementarmedroite(intval($idEquipementJoueur));
			$oUniteJoueur->setEquipementarmegauche(0);
		}		
		//sauvegarde de l'Unite
		self::update($oUniteJoueur);
	}

	/**
	 * Recherche d'une unite engagee au corps-a-corps avec l'unite_joueur
	 * @param object $oUnite
	 */
	public function fightLockOn($oUniteJoueur) {
		ManagerUnite::getInstance()->fightLockOn($oUniteJoueur);
// 		ManagerTile::getInstance()->setCasesAdjacentes($oUniteJoueur->getTileObject(), $oUniteJoueur->getTileObject()->getCarte());
// 		foreach (ManagerTile::getInstance()->getCasesAdjacentes() AS $oCase) {
// 			//si une case adjacente a celle de l'unite est occupee par une unite,
// 			//alors on considere l'unite bloquee et ne pouvant pas tirer ou être ciblée
// 			if ($oCase->getUnite() > 0 || $oCase->getUnite_joueur() > 0) {
// 				return true;
// 			}
// 		}
// 		//aucune unite engagee
// 		return false;
	}
	
	public function testCarac($oUniteJoueur,$carac) {
		$jetDes = lanceDes2(array("1D6"));
		$method = 'get'.ucfirst($carac);
		if ($jetDes <= $oUniteJoueur->$method()) {
			return true;
		} else {
			return false;
		}
	}
	
	public function getPlayerUnitsInGame($idCarte) {
		//1) Liste des Unite
		//2) Liste des Unite_joueur
		//3) Merge des liste
		//4) Retour de la liste
	}
	/*[/TAG-Unite_joueur21]*/


}
?>