<?php
		//Generated by ManagerGenerator::generate()
class ManagerMessage {
	/** Instance de la classe (managerMessage) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Message) */
	private static $_aListeMessage = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Message11]*/	/*[/TAG-Message11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryMessage::getFromTableMessage($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryMessage::getFromExtTableJoueur($value);
	}

	public function getFromExtTableId_auteur_message($idid_auteur_message=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryMessage::getFromExtTableId_auteur_message($idid_auteur_message);
	}

	public function deleteCompositeLinksFromId_auteur_message($idid_auteur_message) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM message WHERE id_auteur_message = '.$idid_auteur_message;
	}

	public function getFromExtTableContenu_message($idcontenu_message=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryMessage::getFromExtTableContenu_message($idcontenu_message);
	}

	public function deleteCompositeLinksFromContenu_message($idcontenu_message) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM message WHERE contenu_message = '.$idcontenu_message;
	}

	public function getFromExtTableDate_creation_message($iddate_creation_message=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryMessage::getFromExtTableDate_creation_message($iddate_creation_message);
	}

	public function deleteCompositeLinksFromDate_creation_message($iddate_creation_message) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM message WHERE date_creation_message = '.$iddate_creation_message;
	}

	public function getFromExtTableDate_modification_message($iddate_modification_message=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryMessage::getFromExtTableDate_modification_message($iddate_modification_message);
	}

	public function deleteCompositeLinksFromDate_modification_message($iddate_modification_message) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM message WHERE date_modification_message = '.$iddate_modification_message;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Message) {
			$oMessage = new Message($object['id'],$object['id_parent'],$object['id_auteur_message'],$object['contenu_message'],$object['date_creation_message'],$object['date_modification_message']);
		} else {
			$oMessage = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oMessage->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Message)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Message) {
			$oMessage = new Message($object['id'],$object['id_parent'],$object['id_auteur_message'],$object['contenu_message'],$object['date_creation_message'],$object['date_modification_message']);
		} else {
			$oMessage = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['message']) && sizeof($_SESSION['message']->compareTo($oMessage)) > 0) {
			$_SESSION['message'] = $oMessage;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oMessage->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Message) {
			$oMessage = new Message($object['id'],$object['id_parent'],$object['id_auteur_message'],$object['contenu_message'],$object['date_creation_message'],$object['date_modification_message']);
		} else {
			$oMessage = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oMessage->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Message();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeMessage); $i++) {
			$object = $this -> _aListeMessage[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Message de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getMessageVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Message();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Message21]*/	/*[/TAG-Message21]*/


}
?>