<?php
		//Generated by ManagerGenerator::generate()
class ManagerTroupecomposition {
	/** Instance de la classe (managerTroupecomposition) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Troupecomposition) */
	private static $_aListeTroupecomposition = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Troupecomposition11]*/	/*[/TAG-Troupecomposition11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryTroupecomposition::getFromTableTroupecomposition($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryTroupecomposition::getFromExtTableJoueur($value);
	}

	public function getFromExtTableTroupe($idtroupe=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryTroupecomposition::getFromExtTableTroupe($idtroupe);
	}

	public function deleteCompositeLinksFromTroupe($idtroupe) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM troupecomposition WHERE troupe = '.$idtroupe;
	}

	public function getFromExtTableUnite_joueur($idunite_joueur=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryTroupecomposition::getFromExtTableUnite_joueur($idunite_joueur);
	}

	public function deleteCompositeLinksFromUnite_joueur($idunite_joueur) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM troupecomposition WHERE unite_joueur = '.$idunite_joueur;
	}

	public function getFromExtTableHero($idhero=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryTroupecomposition::getFromExtTableHero($idhero);
	}

	public function deleteCompositeLinksFromHero($idhero) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM troupecomposition WHERE hero = '.$idhero;
	}

	public function getFromExtTableHeros($idheros=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryTroupecomposition::getFromExtTableHeros($idheros);
	}

	public function deleteCompositeLinksFromHeros($idheros) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM troupecomposition WHERE heros = '.$idheros;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Troupecomposition) {
			$oTroupecomposition = new Troupecomposition($object['id'],$object['troupe'],$object['unite_joueur'],$object['hero'],$object['heros']);
		} else {
			$oTroupecomposition = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oTroupecomposition->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Troupecomposition)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Troupecomposition) {
			$oTroupecomposition = new Troupecomposition($object['id'],$object['troupe'],$object['unite_joueur'],$object['hero'],$object['heros']);
		} else {
			$oTroupecomposition = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['troupecomposition']) && sizeof($_SESSION['troupecomposition']->compareTo($oTroupecomposition)) > 0) {
			$_SESSION['troupecomposition'] = $oTroupecomposition;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oTroupecomposition->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Troupecomposition) {
			$oTroupecomposition = new Troupecomposition($object['id'],$object['troupe'],$object['unite_joueur'],$object['hero'],$object['heros']);
		} else {
			$oTroupecomposition = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oTroupecomposition->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Troupecomposition();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeTroupecomposition); $i++) {
			$object = $this -> _aListeTroupecomposition[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Troupecomposition de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getTroupecompositionVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Troupecomposition();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Troupecomposition21]*/	/*[/TAG-Troupecomposition21]*/


}
?>