<?php
		//Generated by ManagerGenerator::generate()
class ManagerCarteedit {
	/** Instance de la classe (managerCarteedit) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Carteedit) */
	private static $_aListeCarteedit = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Carteedit11]*/	/*[/TAG-Carteedit11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryCarteedit::getFromTableCarteedit($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryCarteedit::getFromExtTableJoueur($value);
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Carteedit) {
			$oCarteedit = new Carteedit($object['id'],$object['nom'],$object['nb_cases_x'],$object['nb_cases_y']);
		} else {
			$oCarteedit = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oCarteedit->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Carteedit)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Carteedit) {
			$oCarteedit = new Carteedit($object['id'],$object['nom'],$object['nb_cases_x'],$object['nb_cases_y']);
		} else {
			$oCarteedit = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['carteedit']) && sizeof($_SESSION['carteedit']->compareTo($oCarteedit)) > 0) {
			$_SESSION['carteedit'] = $oCarteedit;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oCarteedit->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Carteedit) {
			$oCarteedit = new Carteedit($object['id'],$object['nom'],$object['nb_cases_x'],$object['nb_cases_y']);
		} else {
			$oCarteedit = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oCarteedit->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Carteedit();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeCarteedit); $i++) {
			$object = $this -> _aListeCarteedit[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Carteedit de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getCarteeditVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Carteedit();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Carteedit21]*/
	
	    /**
         *  Methode pour recuperer une zone deffinie par les 4 points en parametres
         * @param <type> $xDebut
         * @param <type> $xFin
         * @param <type> $yDebut
         * @param <type> $yFin
         */
        public function getCasesCarteFromRange($idcarte,$xDebut=0,$xFin=0,$yDebut=0,$yFin=0) {
			return FactoryTile::getCasesCarteFromRange($idcarte,$xDebut,$xFin,$yDebut,$yFin);
		}
	
		/**
		 * Methode retournant la liste des cartes en edition
		 */
		public function getCartesEnEdition() {
			return FactoryCarte::getCartesEnEdition();
		}
	
		/**
		 * Methode retournant la carte en edition choisie
		 */
		public function getCarteEnEdition($idCarte) {
			return FactoryCarte::getCarteEnEdition($idCarte);
		}
	/*[/TAG-Carteedit21]*/


}
?>