<?php
		//Generated by ManagerGenerator::generate()
class ManagerStatmembre {
	/** Instance de la classe (managerStatmembre) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Statmembre) */
	private static $_aListeStatmembre = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Statmembre11]*/	/*[/TAG-Statmembre11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryStatmembre::getFromTableStatmembre($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryStatmembre::getFromExtTableJoueur($value);
	}

	public function getFromExtTableMembre($idmembre=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryStatmembre::getFromExtTableMembre($idmembre);
	}

	public function deleteCompositeLinksFromMembre($idmembre) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM statmembre WHERE membre = '.$idmembre;
	}

	public function getFromExtTableHero($idhero=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryStatmembre::getFromExtTableHero($idhero);
	}

	public function deleteCompositeLinksFromHero($idhero) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM statmembre WHERE hero = '.$idhero;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Statmembre) {
			$oStatmembre = new Statmembre($object['id'],$object['membre'],$object['hero'],$object['tues'],$object['morts'],$object['victoires'],$object['defaites']);
		} else {
			$oStatmembre = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oStatmembre->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Statmembre)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Statmembre) {
			$oStatmembre = new Statmembre($object['id'],$object['membre'],$object['hero'],$object['tues'],$object['morts'],$object['victoires'],$object['defaites']);
		} else {
			$oStatmembre = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['statmembre']) && sizeof($_SESSION['statmembre']->compareTo($oStatmembre)) > 0) {
			$_SESSION['statmembre'] = $oStatmembre;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oStatmembre->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Statmembre) {
			$oStatmembre = new Statmembre($object['id'],$object['membre'],$object['hero'],$object['tues'],$object['morts'],$object['victoires'],$object['defaites']);
		} else {
			$oStatmembre = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oStatmembre->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Statmembre();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeStatmembre); $i++) {
			$object = $this -> _aListeStatmembre[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Statmembre de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getStatmembreVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Statmembre();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Statmembre21]*/	/*[/TAG-Statmembre21]*/


}
?>