<?php
		//Generated by ManagerGenerator::generate()
class ManagerChatcarte {
	/** Instance de la classe (managerChatcarte) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Chatcarte) */
	private static $_aListeChatcarte = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Chatcarte11]*/	/*[/TAG-Chatcarte11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryChatcarte::getFromTableChatcarte($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryChatcarte::getFromExtTableJoueur($value);
	}

	public function getFromExtTableMembre($idmembre=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryChatcarte::getFromExtTableMembre($idmembre);
	}

	public function deleteCompositeLinksFromMembre($idmembre) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM chatcarte WHERE membre = '.$idmembre;
	}

	public function getFromExtTableMessage($idmessage=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryChatcarte::getFromExtTableMessage($idmessage);
	}

	public function deleteCompositeLinksFromMessage($idmessage) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM chatcarte WHERE message = '.$idmessage;
	}

	public function getFromExtTableCarte($idcarte=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryChatcarte::getFromExtTableCarte($idcarte);
	}

	public function deleteCompositeLinksFromCarte($idcarte) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM chatcarte WHERE carte = '.$idcarte;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Chatcarte) {
			$oChatcarte = new Chatcarte($object['chat'],$object['membre'],$object['message'],$object['tspost'],$object['carte']);
		} else {
			$oChatcarte = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oChatcarte->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Chatcarte)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Chatcarte) {
			$oChatcarte = new Chatcarte($object['chat'],$object['membre'],$object['message'],$object['tspost'],$object['carte']);
		} else {
			$oChatcarte = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['chatcarte']) && sizeof($_SESSION['chatcarte']->compareTo($oChatcarte)) > 0) {
			$_SESSION['chatcarte'] = $oChatcarte;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oChatcarte->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Chatcarte) {
			$oChatcarte = new Chatcarte($object['chat'],$object['membre'],$object['message'],$object['tspost'],$object['carte']);
		} else {
			$oChatcarte = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oChatcarte->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Chatcarte();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeChatcarte); $i++) {
			$object = $this -> _aListeChatcarte[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Chatcarte de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getChatcarteVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Chatcarte();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Chatcarte21]*/	/*[/TAG-Chatcarte21]*/


}
?>