<?php
		//Generated by ManagerGenerator::generate()
class ManagerDroit_membre {
	/** Instance de la classe (managerDroit_membre) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Droit_membre) */
	private static $_aListeDroit_membre = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Droit_membre11]*/	/*[/TAG-Droit_membre11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryDroit_membre::getFromTableDroit_membre($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryDroit_membre::getFromExtTableJoueur($value);
	}

	public function getFromExtTableDroit($iddroit=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryDroit_membre::getFromExtTableDroit($iddroit);
	}

	public function deleteCompositeLinksFromDroit($iddroit) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM droit_membre WHERE droit = '.$iddroit;
	}

	public function getFromExtTableMembre($idmembre=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryDroit_membre::getFromExtTableMembre($idmembre);
	}

	public function deleteCompositeLinksFromMembre($idmembre) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM droit_membre WHERE membre = '.$idmembre;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Droit_membre) {
			$oDroit_membre = new Droit_membre($object['droit'],$object['membre']);
		} else {
			$oDroit_membre = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oDroit_membre->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Droit_membre)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Droit_membre) {
			$oDroit_membre = new Droit_membre($object['droit'],$object['membre']);
		} else {
			$oDroit_membre = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['droit_membre']) && sizeof($_SESSION['droit_membre']->compareTo($oDroit_membre)) > 0) {
			$_SESSION['droit_membre'] = $oDroit_membre;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oDroit_membre->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Droit_membre) {
			$oDroit_membre = new Droit_membre($object['droit'],$object['membre']);
		} else {
			$oDroit_membre = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oDroit_membre->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Droit_membre();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeDroit_membre); $i++) {
			$object = $this -> _aListeDroit_membre[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Droit_membre de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getDroit_membreVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Droit_membre();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Droit_membre21]*/	/*[/TAG-Droit_membre21]*/


}
?>