<?php
		//Generated by ManagerGenerator::generate()
class ManagerModule {
	/** Instance de la classe (managerModule) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Module) */
	private static $_aListeModule = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Module11]*/	/*[/TAG-Module11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryModule::getFromTableModule($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryModule::getFromExtTableJoueur($value);
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Module) {
			$oModule = new Module($object['id'],$object['nom'],$object['actif']);
		} else {
			$oModule = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oModule->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Module)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Module) {
			$oModule = new Module($object['id'],$object['nom'],$object['actif']);
		} else {
			$oModule = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['module']) && sizeof($_SESSION['module']->compareTo($oModule)) > 0) {
			$_SESSION['module'] = $oModule;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oModule->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Module) {
			$oModule = new Module($object['id'],$object['nom'],$object['actif']);
		} else {
			$oModule = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oModule->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Module();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeModule); $i++) {
			$object = $this -> _aListeModule[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Module de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getModuleVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Module();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Module21]*/
	
	public function getModulesActifs() {
		$aListeModules = $this->getById();
		$aListe = array();
		foreach ($aListeModules AS $module) {
			if ($module->getActif() == 2) {
				$aListe[] = $module;
			}
		}
		return $aListe;
	}
	
	public function getModulesDev() {
		$aListeModules = $this->getById();
		$aListe = array();
		foreach ($aListeModules AS $module) {
			if ($module->getActif() == 0) {
				$aListe[] = $module;
			}
		}
		return $aListe;
	}
	/*[/TAG-Module21]*/


}
?>