<?php
		//Generated by ManagerGenerator::generate() on 03/04/2017 15:27:38
class ManagerEquipement {
	/** Instance de la classe (managerEquipement) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Equipement) */
	private static $_aListeEquipement = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Equipement11]*/	/*[/TAG-Equipement11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct() on 03/04/2017 15:27:38
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct() on 03/04/2017 15:27:38
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance() on 03/04/2017 15:27:38
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone() on 03/04/2017 15:27:38
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion() on 03/04/2017 15:27:38
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet() on 03/04/2017 15:27:38
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet() on 03/04/2017 15:27:38
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById() on 03/04/2017 15:27:38
		return FactoryEquipement::getFromTableEquipement($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId() on 03/04/2017 15:27:38
		return FactoryEquipement::getFromExtTableJoueur($value);
	}

	public function getFromExtTableCategorie($idcategorie=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 03/04/2017 15:27:38
		/* Appel de la methode de la Fabrique */
		return FactoryEquipement::getFromExtTableCategorie($idcategorie);
	}

	public function deleteCompositeLinksFromCategorie($idcategorie) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 03/04/2017 15:27:38
		//TODO
	}

	public function getFromExtTableGabarit($idgabarit=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 03/04/2017 15:27:38
		/* Appel de la methode de la Fabrique */
		return FactoryEquipement::getFromExtTableGabarit($idgabarit);
	}

	public function deleteCompositeLinksFromGabarit($idgabarit) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 03/04/2017 15:27:38
		//TODO
	}

	public function getFromExtTableType($idtype=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 03/04/2017 15:27:38
		/* Appel de la methode de la Fabrique */
		return FactoryEquipement::getFromExtTableType($idtype);
	}

	public function deleteCompositeLinksFromType($idtype) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 03/04/2017 15:27:38
		//TODO
	}

	public function getFromExtTableTile($idtile=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 03/04/2017 15:27:38
		/* Appel de la methode de la Fabrique */
		return FactoryEquipement::getFromExtTableTile($idtile);
	}

	public function deleteCompositeLinksFromTile($idtile) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 03/04/2017 15:27:38
		//TODO
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete() on 03/04/2017 15:27:38
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Equipement) {
			$oEquipement = new Equipement($object['id'],$object['nom'],$object['description'],$object['categorie'],$object['cp'],$object['lp'],$object['mtcp'],$object['mtlp'],$object['dommage'],$object['msvg'],$object['gabarit'],$object['type'],$object['fo'],$object['sauvegarde'],$object['mmvt'],$object['encombrement'],$object['deux_mains'],$object['cout'],$object['date_creation'],$object['chemin'],$object['tile'],$object['usure'],$object['demontable'],$object['date_fin_reparation'],$object['ingame']);
		} else {
			$oEquipement = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oEquipement->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Equipement)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate() on 03/04/2017 15:27:38
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Equipement) {
			$oEquipement = new Equipement($object['id'],$object['nom'],$object['description'],$object['categorie'],$object['cp'],$object['lp'],$object['mtcp'],$object['mtlp'],$object['dommage'],$object['msvg'],$object['gabarit'],$object['type'],$object['fo'],$object['sauvegarde'],$object['mmvt'],$object['encombrement'],$object['deux_mains'],$object['cout'],$object['date_creation'],$object['chemin'],$object['tile'],$object['usure'],$object['demontable'],$object['date_fin_reparation'],$object['ingame']);
		} else {
			$oEquipement = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['equipement']) && sizeof($_SESSION['equipement']->compareTo($oEquipement)) > 0) {
			$_SESSION['equipement'] = $oEquipement;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oEquipement->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave() on 03/04/2017 15:27:38
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Equipement) {
			$oEquipement = new Equipement($object['id'],$object['nom'],$object['description'],$object['categorie'],$object['cp'],$object['lp'],$object['mtcp'],$object['mtlp'],$object['dommage'],$object['msvg'],$object['gabarit'],$object['type'],$object['fo'],$object['sauvegarde'],$object['mmvt'],$object['encombrement'],$object['deux_mains'],$object['cout'],$object['date_creation'],$object['chemin'],$object['tile'],$object['usure'],$object['demontable'],$object['date_fin_reparation'],$object['ingame']);
		} else {
			$oEquipement = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oEquipement->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy() on 03/04/2017 15:27:38
		/* creation d'un objet de base de la classe */
		$object = new Equipement();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeEquipement); $i++) {
			$object = $this -> _aListeEquipement[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Equipement de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getEquipementVide() {
		//Generated by ManagerGenerator::generateGetObjetVide() on 03/04/2017 15:27:38
		return new Equipement();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Equipement21]*/

	public function setEquipmentsOutOfGame($idCarte) {
		$requete = "UPDATE equipement SET tile = 0, ingame = 0 ";
		$requete .= "WHERE tile IN (SELECT id FROM tile WHERE carte = :carte)";
		database::getInstance()->prepareRequete($requete);
		database::getInstance()->bind(array('carte' => $idcarte));
		return database::getInstance()->executeRequete();
		if (database::getInstance()->executeRequete($requete)) {
	
		} else {
			throw new PDOException('Erreur sur setUnitsOutOfGame (Equipement)');
		}
	}
	
	public function setEquipmentsOutOfCase($idCase) {
		$requete = "UPDATE equipement SET tile = 0 ";
		$requete .= "WHERE tile = :tile".$idCase;
		database::getInstance()->prepareRequete($requete);
		database::getInstance()->bind(array('tile' => $idCase));
		return database::getInstance()->executeRequete();
		if (database::getInstance()->executeRequete($requete)) {
	
		} else {
			throw new PDOException('Erreur sur setUnitsOutOfCase (Equipement)');
		}
	}
	
	public function attaque($attaquant,$defenseur) {
		if (empty($attaquant) || empty($defenseur)) {
			alerte("ERREUR, Impossible, un des deux beligerent n'existe pas");
			return;
		}
		
		//20170316,CBA, mise en commun des codes Equipement / Equipement_Joueur
		if ($attaquant instanceof Equipement_Joueur) {
			//Equipement_Joueur
			$oCaseEquipement = FactoryTile::getFromExtTableEquipementjoueur($attaquant->getId());
		} else {
			//Equipement simple
			$oCaseEquipement = FactoryTile::getFromExtTableEquipement($attaquant->getId());
		}
		
		if (empty($oCaseEquipement)) {
			alerte("L'unite attaquante (".$attaquant->getNom().") n'est pas sur une table de jeu");
			return;
		}
		
		//Preparation pôur l'ActionAttaque
		$attaquant->chargeCategorie();
		$oAttaque = new Actionattaque($attaquant->getCategorieObject()->getNom());
		
		if (is_null($defenseur)) {
			debug("attaque avec equipement explosif sans contact",true);
			
			//Liste des cases occupees
			$listeCasesAAttaquer = $this->isThereEnnemies($oCaseEquipement,$attaquant->getPorteTotale());
			
			//Maintenant il faut parcourir la liste des unites presentes et lancer les attaques
			foreach ($listeCasesAAttaquer AS $oCase) {
				$resultCompare = $oCase->compareTo($oCaseEquipement);
				if (!empty($resultCompare)) {
					if (!empty($oAttaque)) {
						debug("attaque avec equipement");
						$oAttaque->attaque($attaquant,$oCase->getUnite());
						if ($oAttaque->getBlessures() > 0) {
							debug("Blessure(s) du tir rapide: ".$oAttaque->getBlessures());
							debug("Assignation des blessures");
							$defenseur->encaisse($oAttaque->getBlessures());
							if ($defenseur->getPdv() < 0) {
								debug("Unit&eacute; d&eacute;truite.");
							}
						} else {
							debug("Pas de blessures");
						}
					}
				}
			}
		} else {
			//au contact ???
			debug("Attaque avec &eacute;quipement au contact",true);
			$oAttaque->attaque($attaquant,$defenseur);
			if ($oAttaque->getBlessures() > 0) {
				debug("Blessure(s) du tir rapide: ".$oAttaque->getBlessures(),true);
				debug("Assignation des blessures",true);
				if ($attaquant instanceof Equipement && $attaquant->getGabarit() > 0) {
					debug("Application du gabarit",true);
					$oActionGabarit = new Actiongabarit($attaquant->getGabarit());
					$aCasesGabarit = $oActionGabarit->getListeCasesgabarit($attaquant->getTileObject());
					debug("Recherche unite sur les cases du gabarit",true);
					foreach ($aCasesGabarit AS $oCase) {
						if ($oCase->getUnite() > 0) {
							debug("Unite sur case (".$oCase->getX()." / ".$oCase->getY()."), => Unite (".$oCase->getUniteObject()->getNom().", ID ".$oCase->getUniteObject()->getId().")",true);
							$oCase->getUniteObject()->encaisse($oAttaque->getBlessures());
							if ($oCase->getUniteObject()->getPdv() <= 0) {
								debug($oCase->getUniteObject()->getNom()." est d&eacute;truite",true);
							}
						}
						if ($oCase->getUnite_joueur() > 0) {
							debug("Unite joueur sur case (".$oCase->getX()." / ".$oCase->getY()."), => Unite joueur (".$oCase->getUnite_joueurObject()->getNom().", ID ".$oCase->getUnite_joueurObject()->getId().")",true);
							$oCase->getUnite_joueurObject()->encaisse($oAttaque->getBlessures());
							if ($oCase->getUnite_joueurObject()->getPdv() <= 0) {
								debug($oCase->getUnite_joueurObject()->getNom()." est d&eacute;truite",true);
							}
						}
					}
				} else {
					//Pas de gabarit
					$defenseur->encaisse($oAttaque->getBlessures());
					if ($defenseur->getPdv() < 0) {
						debug("Unit&eacute; d&eacute;truite.",true);
					}					
				}

			} else {
				debug("Pas de blessures",true);
			}
		}
		
		//-------
		//-------
		
// 		if ($attaquant instanceof Equipement_joueur) {
// 			ManagerEquipement_joueur::getInstance()->attaque($attaquant,$defenseur);
// 		}
// 		if ($attaquant instanceof Equipement) {
			// C'est un equipement que a l'action d'attaque (Ex: mine)			
// 			$oCaseEquipement = FactoryTile::getFromExtTableEquipement($attaquant->getId());


// 			if (empty($oCaseEquipement)) {
// 				alerte("L'unite attaquante (".$attaquant->getNom().") n'est pas sur une table de jeu");
// 				return;
// 			}
// 			$attaquant->chargeCategorie();
			
			//preparation de l'objet attaque
// 			$oAttaque = new Actionattaque($attaquant->getCategorieObject()->getNom());
			
// 			$rayon = $attaquant->getPorteTotale();

// 			if (is_null($defenseur)) {
// 				debug("attaque avec equipement explosif sans contact");
				// la liste des cases dans le rayon de l'arme
// 				$xMin = $oCaseEquipement->getX() - intval(max($rayon));
// 				if ($xMin < 0) {
// 					$xMin = 0;
// 				}
// 				$xMax = $oCaseEquipement->getX() + intval(max($rayon));
// 				$yMin = $oCaseEquipement->getY() - intval(max($rayon));
// 				if ($yMin < 0) {
// 					$yMin = 0;
// 				}
// 				$yMax = $oCaseEquipement->getY() + intval(max($rayon));
					
// 				$listeCasesAAttaquer = FactoryTile::getBusyCasesCarteFromRange($oCaseEquipement->getIdcarte(),$xMin,$xMax,$yMin,$yMax);
				
// 				$listeCasesAAttaquer = $this->isThereEnnemies($oCaseAttaquant,$attaquant->getPorteTotale());
				
				//Maintenant il faut parcourir la liste des unites presentes et lancer les attaques
// 				foreach ($listeCasesAAttaquer AS $oCase) {
// 					$resultCompare = $oCase->compareTo($oCaseEquipement);
// 					if (!empty($resultCompare)) {
// 						if (!empty($oAttaque)) {
// 							debug("attaque avec equipement");
// 							$oAttaque->attaque($attaquant,$oCase->getUnite());
// 							if ($oAttaque->getBlessures() > 0) {
// 								debug("Blessure(s) du tir rapide: ".$oAttaque->getBlessures());
// 								debug("Assignation des blessures");
// 								$defenseur->encaisse($oAttaque->getBlessures());
// 								if ($defenseur->getPdv() < 0) {
// 									debug("Unit&eacute; d&eacute;truite.");
// 								}
// 							} else {
// 								debug("Pas de blessures");
// 							}
// 						}
// 					}
// 				}
// 			} else {
// 				//au contact ???
// 				debug("attaque avec equipement au contact");
// 				$oAttaque->attaque($attaquant,$defenseur);
// 				if ($oAttaque->getBlessures() > 0) {
// 					debug("Blessure(s) du tir rapide: ".$oAttaque->getBlessures());
// 					debug("Assignation des blessures");
// 					$defenseur->encaisse($oAttaque->getBlessures());
// 					if ($defenseur->getPdv() < 0) {
// 						debug("Unit&eacute; d&eacute;truite.");
// 					}
// 				} else {
// 					debug("Pas de blessures");
// 				}
// 			}
// 		}
	}
	
	/**
	 * Methode de recherche d'ennemis dans le rayon de l'arme de l'unite
	 * @param Tile $oCaseAttaquant
	 * @param int $idCarte
	 * @param array $rayon
	 * @return array <multitype:Tile, multitype:Tile >
	 */
	public function isThereEnnemies($oCaseAttaquant,$rayon) {
		// la liste des cases dans le rayon de l'arme
		$xMin = $oCaseAttaquant->getX() - intval(max($rayon));
		if ($xMin < 0) {
			$xMin = 0;
		}
		$xMax = $oCaseAttaquant->getX() + intval(max($rayon));
		$yMin = $oCaseAttaquant->getY() - intval(max($rayon));
		if ($yMin < 0) {
			$yMin = 0;
		}
		$yMax = $oCaseAttaquant->getY() + intval(max($rayon));
	
		return FactoryTile::getBusyCasesCarteFromRange($oCaseAttaquant->getCarte(),$xMin,$xMax,$yMin,$yMax);
	}
	
	/**
	 * Methode de remise en jeu d'un equipement
	 * @param unknown $oUnite
	 * @throws PDOException
	 */
	public function setEquipementInGame($oEquipement,$idTile) {
		if (!($oEquipement instanceof Equipement)) {
// 			ManagerUnite_joueur::getInstance()->setUnitInGame($oUnite);
		} else {
			$retour = true;
			$requete = "UPDATE equipement SET tile = :tile, ingame = 1 ";
			$requete .= "WHERE id =  :id";
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('id' => $oEquipement->getId(),'tile' => $idTile));
			//UPDATE retourne le nombre de ligne modifiees
			$retour = database::getInstance()->executeRequete();
			debug("nb lignes affectees = ".database::getInstance()->rowCount(),true);
			//meme chose sur la case
			$requete = "UPDATE tile SET equipement = :equipement ";
			$requete .= "WHERE id = :id";
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('id' => $idTile,'equipement' => $oEquipement->getId()));
				//UPDATE retourne le nombre de ligne modifiees
// 				return database::getInstance()->executeRequete();
			$retour = database::getInstance()->executeRequete();
		}
		return $retour;
	}
	
	public function setEquipementOutOfGame($oEquipement) {
		if ($oEquipement instanceof Equipement && !$oEquipement instanceof Equipement_joueur) {
// 			ManagerUnite::getInstance()->setUnitOutOfGame($oUnite);
		} else {
			$requete = "UPDATE equipement SET tile = 0,ingame = 0 ";
			$requete .= "WHERE id = :id".$oUnite->getId();
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('id' => $oEquipement->getId()));
			$retour = database::getInstance()->executeRequete();
			//meme chose sur la case
			$requete = "UPDATE tile SET equipement = 0 ";
			$requete .= "WHERE equipement = ".$oEquipement->getId();
			database::getInstance()->prepareRequete($requete);
			database::getInstance()->bind(array('equipement' => $oEquipement->getId()));
		}
	}
	
// 	public function getByType($nomType) {
// 		$oType = ManagerType::getInstance()->getByType($nomType);
// 		debug($oType);
// 		$oCategorie = ManagerCategorie::getInstance()->getFromExtTableType($oType->getId());
// 		debug($oCategorie);
// 		return FactoryEquipement::getFromExtTable;
		
// 	}

	public function getCourtePortee($oEquipement) {
		if ($oEquipement instanceof Equipement || $oEquipement instanceof Equipement_joueur) {
// 			ManagerEquipement_joueur::getInstance()->getCourtePortee($oEquipement);
// 		} else {
			return explode('-',$oEquipement->getCp());
		}
	}

	public function getLonguePortee($oEquipement) {
		if ($oEquipement instanceof Equipement || $oEquipement instanceof Equipement_joueur) {
// 			ManagerEquipement_joueur::getInstance()->getLonguePortee($oEquipement);
// 		} else {
			return explode('-',$oEquipement->getLp());
		}
	}
	/*[/TAG-Equipement21]*/


}
?>