<?php
		//Generated by ManagerGenerator::generate()
class ManagerArene {
	/** Instance de la classe (managerArene) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Arene) */
	private static $_aListeArene = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Arene11]*/	/*[/TAG-Arene11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryArene::getFromTableArene($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryArene::getFromExtTableJoueur($value);
	}

	public function getFromExtTableNb_joueur_min($idnb_joueur_min=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryArene::getFromExtTableNb_joueur_min($idnb_joueur_min);
	}

	public function deleteCompositeLinksFromNb_joueur_min($idnb_joueur_min) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM arene WHERE nb_joueur_min = '.$idnb_joueur_min;
	}

	public function getFromExtTableNb_joueur_max($idnb_joueur_max=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryArene::getFromExtTableNb_joueur_max($idnb_joueur_max);
	}

	public function deleteCompositeLinksFromNb_joueur_max($idnb_joueur_max) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM arene WHERE nb_joueur_max = '.$idnb_joueur_max;
	}

	public function getFromExtTableFantassins_min($idfantassins_min=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryArene::getFromExtTableFantassins_min($idfantassins_min);
	}

	public function deleteCompositeLinksFromFantassins_min($idfantassins_min) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM arene WHERE fantassins_min = '.$idfantassins_min;
	}

	public function getFromExtTableFantassins_max($idfantassins_max=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryArene::getFromExtTableFantassins_max($idfantassins_max);
	}

	public function deleteCompositeLinksFromFantassins_max($idfantassins_max) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM arene WHERE fantassins_max = '.$idfantassins_max;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Arene) {
			$oArene = new Arene($object['titre'],$object['nb_joueur_min'],$object['nb_joueur_max'],$object['fantassins_min'],$object['fantassins_max'],$object['motorise_min'],$object['motorise_max'],$object['aerien_min'],$object['aerien_max']);
		} else {
			$oArene = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oArene->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Arene)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Arene) {
			$oArene = new Arene($object['titre'],$object['nb_joueur_min'],$object['nb_joueur_max'],$object['fantassins_min'],$object['fantassins_max'],$object['motorise_min'],$object['motorise_max'],$object['aerien_min'],$object['aerien_max']);
		} else {
			$oArene = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['arene']) && sizeof($_SESSION['arene']->compareTo($oArene)) > 0) {
			$_SESSION['arene'] = $oArene;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oArene->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Arene) {
			$oArene = new Arene($object['titre'],$object['nb_joueur_min'],$object['nb_joueur_max'],$object['fantassins_min'],$object['fantassins_max'],$object['motorise_min'],$object['motorise_max'],$object['aerien_min'],$object['aerien_max']);
		} else {
			$oArene = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oArene->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Arene();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeArene); $i++) {
			$object = $this -> _aListeArene[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Arene de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getAreneVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Arene();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Arene21]*/	/*[/TAG-Arene21]*/


}
?>