<?php
		//Generated by ManagerGenerator::generate()
class ManagerDecor_utilise {
	/** Instance de la classe (managerDecor_utilise) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Decor_utilise) */
	private static $_aListeDecor_utilise = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Decor_utilise11]*/	/*[/TAG-Decor_utilise11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryDecor_utilise::getFromTableDecor_utilise($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryDecor_utilise::getFromExtTableJoueur($value);
	}

	public function getFromExtTableDimension($iddimension=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryDecor_utilise::getFromExtTableDimension($iddimension);
	}

	public function deleteCompositeLinksFromDimension($iddimension) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM decor_utilise WHERE dimension = '.$iddimension;
	}

	public function getFromExtTableCamp($idcamp=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryDecor_utilise::getFromExtTableCamp($idcamp);
	}

	public function deleteCompositeLinksFromCamp($idcamp) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM decor_utilise WHERE camp = '.$idcamp;
	}

	public function getFromExtTableCarte($idcarte=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryDecor_utilise::getFromExtTableCarte($idcarte);
	}

	public function deleteCompositeLinksFromCarte($idcarte) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM decor_utilise WHERE carte = '.$idcarte;
	}

	public function getFromExtTableTile($idtile=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryDecor_utilise::getFromExtTableTile($idtile);
	}

	public function deleteCompositeLinksFromTile($idtile) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM decor_utilise WHERE tile = '.$idtile;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Decor_utilise) {
			$oDecor_utilise = new Decor_utilise($object['id'],$object['nom'],$object['description'],$object['chemin'],$object['modificateur_vision'],$object['date_creation'],$object['date_modification'],$object['dimension'],$object['camp'],$object['carte'],$object['tile'],$object['coordonnees']);
		} else {
			$oDecor_utilise = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oDecor_utilise->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Decor_utilise)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Decor_utilise) {
			$oDecor_utilise = new Decor_utilise($object['id'],$object['nom'],$object['description'],$object['chemin'],$object['modificateur_vision'],$object['date_creation'],$object['date_modification'],$object['dimension'],$object['camp'],$object['carte'],$object['tile'],$object['coordonnees']);
		} else {
			$oDecor_utilise = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['decor_utilise']) && sizeof($_SESSION['decor_utilise']->compareTo($oDecor_utilise)) > 0) {
			$_SESSION['decor_utilise'] = $oDecor_utilise;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oDecor_utilise->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Decor_utilise) {
			$oDecor_utilise = new Decor_utilise($object['id'],$object['nom'],$object['description'],$object['chemin'],$object['modificateur_vision'],$object['date_creation'],$object['date_modification'],$object['dimension'],$object['camp'],$object['carte'],$object['tile'],$object['coordonnees']);
		} else {
			$oDecor_utilise = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oDecor_utilise->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Decor_utilise();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeDecor_utilise); $i++) {
			$object = $this -> _aListeDecor_utilise[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Decor_utilise de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getDecor_utiliseVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Decor_utilise();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Decor_utilise21]*/	/*[/TAG-Decor_utilise21]*/


}
?>