<?php
		//Generated by ManagerGenerator::generate()
class ManagerVw_liste_unite_joueur {
	/** Instance de la classe (managerVw_liste_unite_joueur) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Vw_liste_unite_joueur) */
	private static $_aListeVw_liste_unite_joueur = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Vw_liste_unite_joueur11]*/	/*[/TAG-Vw_liste_unite_joueur11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryVw_liste_unite_joueur::getFromTableVw_liste_unite_joueur($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryVw_liste_unite_joueur::getFromExtTableJoueur($value);
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Vw_liste_unite_joueur) {
			$oVw_liste_unite_joueur = new Vw_liste_unite_joueur($object['tutu'],$object['pseudo'],$object['id'],$object['nom']);
		} else {
			$oVw_liste_unite_joueur = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oVw_liste_unite_joueur->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Vw_liste_unite_joueur)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Vw_liste_unite_joueur) {
			$oVw_liste_unite_joueur = new Vw_liste_unite_joueur($object['tutu'],$object['pseudo'],$object['id'],$object['nom']);
		} else {
			$oVw_liste_unite_joueur = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['vw_liste_unite_joueur']) && sizeof($_SESSION['vw_liste_unite_joueur']->compareTo($oVw_liste_unite_joueur)) > 0) {
			$_SESSION['vw_liste_unite_joueur'] = $oVw_liste_unite_joueur;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oVw_liste_unite_joueur->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Vw_liste_unite_joueur) {
			$oVw_liste_unite_joueur = new Vw_liste_unite_joueur($object['tutu'],$object['pseudo'],$object['id'],$object['nom']);
		} else {
			$oVw_liste_unite_joueur = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oVw_liste_unite_joueur->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Vw_liste_unite_joueur();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeVw_liste_unite_joueur); $i++) {
			$object = $this -> _aListeVw_liste_unite_joueur[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Vw_liste_unite_joueur de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getVw_liste_unite_joueurVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Vw_liste_unite_joueur();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Vw_liste_unite_joueur21]*/	/*[/TAG-Vw_liste_unite_joueur21]*/


}
?>