<?php
		//Generated by ManagerGenerator::generate()
class ManagerDimension {
	/** Instance de la classe (managerDimension) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Dimension) */
	private static $_aListeDimension = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Dimension11]*/	/*[/TAG-Dimension11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct()
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct()
		/* TODO ??*/
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance()
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone()
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion()
		self::$_oConnexion = database::getInstance();/* pas besoin de parametrer, un manager arrive apres la conf */
	}

	public function __set($name,$value) {
		//Generated by ManagerGenerator::generateSet()
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet()
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($value=-1) {
		//Generated by ManagerGenerator::generateGetById()
		return FactoryDimension::getFromTableDimension($value);
	}

	public function getByJoueurId($value) {
		//Generated by ManagerGenerator::generateGetByJoueurId()
		return FactoryDimension::getFromExtTableJoueur($value);
	}

	public function getFromExtTableType($idtype=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK()
		/* Appel de la methode de la Fabrique */
		return FactoryDimension::getFromExtTableType($idtype);
	}

	public function deleteCompositeLinksFromType($idtype) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks()
		$requete = 'DELETE FROM dimension WHERE type = '.$idtype;
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Dimension) {
			$oDimension = new Dimension($object['id'],$object['nom'],$object['type'],$object['largeur'],$object['longueur'],$object['surface']);
		} else {
			$oDimension = $object;
		}
		/* Appel de la methode delete de l'objet */
		/* Tout se passe dans une transaction ouverte plus haut */
			/* Execution de la requete */
		if (database::getInstance()->executeRequete($oDimension->delete())) {
			/* Requete OK */
			return true;
		} else {
			/* Requete NOK lancement d'une exception PDO */
			throw new PDOException('Erreur sur delete (Dimension)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Dimension) {
			$oDimension = new Dimension($object['id'],$object['nom'],$object['type'],$object['largeur'],$object['longueur'],$object['surface']);
		} else {
			$oDimension = $object;
		}
		/* Maintenant on compare avec celle en session */
		if (!empty($_SESSION['dimension']) && sizeof($_SESSION['dimension']->compareTo($oDimension)) > 0) {
			$_SESSION['dimension'] = $oDimension;
		}
		/* on update car les objets sont different */
		return database::getInstance()->executeRequete($oDimension->update());
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave()
		/* Verification */
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		/* si ce n'est pas une instance de la classe, on la cree */
		if (! $object instanceof Dimension) {
			$oDimension = new Dimension($object['id'],$object['nom'],$object['type'],$object['largeur'],$object['longueur'],$object['surface']);
		} else {
			$oDimension = $object;
		}
		/* Appel de la methode update de l'objet */
		return database::getInstance()->executeRequete($oDimension->save());
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy()
		/* creation d'un objet de base de la classe */
		$object = new Dimension();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeDimension); $i++) {
			$object = $this -> _aListeDimension[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Dimension de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getDimensionVide() {
		//Generated by ManagerGenerator::generateGetObjetVide()
		return new Dimension();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Dimension21]*/
	
	public function getByLargeurAndLongueur($largeur,$longueur) {
		if (!is_numeric($largeur)) {
			throw new Exception(get_class($this).": la largeur doit &ecirc;tre un nombre.", E_USER_ERROR);
		}
		if (!is_numeric($longueur)) {
			throw new Exception(get_class($this).": la longueur doit &ecirc;tre un nombre.", E_USER_ERROR);
		}
		if (!is_int($largeur)) {
			throw new Exception(get_class($this).": la largeur doit &ecirc;tre un entier.", E_USER_ERROR);
		}
		if (!is_int($longueur)) {
			throw new Exception(get_class($this).": la longueur doit &ecirc;tre un entier.", E_USER_ERROR);
		}
		return FactoryDimension::getByLangeurAndLongueur($largeur, $longueur);
	}
	
	public function getByLargeur($largeur) {
		if (!is_numeric($largeur)) {
			throw new Exception(get_class($this).": la largeur doit &ecirc;tre un nombre.", E_USER_ERROR);
		}
		if (!is_int($largeur)) {
			throw new Exception(get_class($this).": la largeur doit &ecirc;tre un entier.", E_USER_ERROR);
		}
		return FactoryDimension::getByLangeur($largeur);
	}
	
	public function getByLongueur($longueur) {
		if (!is_numeric($longueur)) {
			throw new Exception(get_class($this).": la longueur doit &ecirc;tre un nombre.", E_USER_ERROR);
		}
		if (!is_int($longueur)) {
			throw new Exception(get_class($this).": la longueur doit &ecirc;tre un entier.", E_USER_ERROR);
		}
		return FactoryDimension::getByLongueur($longueur);
	}
	/*[/TAG-Dimension21]*/


}
?>