<?php
		//Generated by ManagerGenerator::generate() on 02/08/2017 14:24:29
class ManagerMontest {
	/** Instance de la classe (managerMontest) */
	private static $_instance = null;

	/** Connexion a la base de donnees (database) */
	private static $_oConnexion = null;

	/** Liste des objet de la classe (Montest) */
	private static $_aListeMontest = array();

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Montest11]*/	/*[/TAG-Montest11]*/


	protected function __construct() {
		//Generated by ManagerGenerator::generateConstruct() on 02/08/2017 14:24:29
	}

	public function __destruct() {
		//Generated by ManagerGenerator::generateDestruct() on 02/08/2017 14:24:29
		// TODO ??
	}

	public static function getInstance() {
		//Generated by ManagerGenerator::generateGetInstance() on 02/08/2017 14:24:29
		if (is_null(self::$_instance)) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	public function __clone() {
		//Generated by ManagerGenerator::generateClone() on 02/08/2017 14:24:29
		throw new Exception(get_class($this).": Le clonage n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function setConnexion() {
		//Generated by ManagerGenerator::generateSetConnexion() on 02/08/2017 14:24:29
		self::$_oConnexion = database::getInstance();// pas besoin de parametrer, un manager arrive apres la conf
	}

	public function __set($name,$id) {
		//Generated by ManagerGenerator::generateSet() on 02/08/2017 14:24:29
		throw new Exception(get_class($this).": Le set 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function __get($name) {
		//Generated by ManagerGenerator::generateGet() on 02/08/2017 14:24:29
		throw new Exception(get_class($this).": Le get 'noname' n'est pas autoris&eacute;", E_USER_ERROR);
	}

	public function getById($id=-1) {
		//Generated by ManagerGenerator::generateGetById() on 02/08/2017 14:24:29
		if ($id == -1) {
			//Toute les informations
			return FactoryMontest::getFromTableMontest($id);
		} else {
			//Verification si l'objet n'est pas en memoire
			if ($id > 0 && !array_key_exists($id,self::$_aListeMontest)) {
				self::$_aListeMontest[$id] = FactoryMontest::getFromTableMontest($id);
			}
		}
		return self::$_aListeMontest[$id];
	}

	public function getFromExtTableTest($test=-1) {
		//Generated by ManagerGenerator::generateGetFromTableFromFK() on 02/08/2017 14:24:29
		//Verification en memoire
		foreach (self::$_aListeMontest AS $oMontest) {
			if ($oMontest->getTest() == $test) {
				return $oMontest;
			}
		}
		// Appel de la methode de la Fabrique
		$oMontest = FactoryMontest::getFromExtTableTest($test);
		// Memorisation pour plus tard
		self::$_aListeMontest[$oMontest->getId()] = $oMontest;
		// Renvoie de la donnee
		return $oMontest;
	}

	public function deleteCompositeLinksFromTest($idtest) {
		//Generated by ManagerGenerator::generateDeleteCompositeLinks() on 02/08/2017 14:24:29
		//TODO
	}

	public function delete($object=array()) {
		//Generated by ManagerGenerator::generateDelete() on 02/08/2017 14:24:29
		// Verification
		if (empty($object)) {
			throw new Exception(get_class($this).": La suppression se fait sur un objet.", E_USER_ERROR);
		}
		// si ce n'est pas une instance de la classe, on la cree
		if (! $object instanceof Montest) {
			$oMontest = new Montest($object['id'],$object['nom'],$object['prenom'],$object['test']);
		} else {
			$oMontest = $object;
		}
		// Appel de la methode delete de l'objet
		// Tout se passe dans une transaction ouverte plus haut
			// Execution de la requete
		if (database::getInstance()->executeRequete($oMontest->delete())) {
			// Requete OK
			unset(self::$_aListeMontest[$oMontest->getId()]);
			return true;
		} else {
			// Requete NOK lancement d'une exception PDO
			throw new PDOException('Erreur sur delete (Montest)');
		}
	}

	public function update($object=array()) {
		//Generated by ManagerGenerator::generateUpdate() on 02/08/2017 14:24:29
		// Verification
		if (empty($object)) {
			throw new Exception(get_class($this).": la mise &agrave; jour se fait sur un objet.", E_USER_ERROR);
		}
		// si ce n'est pas une instance de la classe, on la cree
		if (! $object instanceof Montest) {
			$oMontest = new Montest($object['id'],$object['nom'],$object['prenom'],$object['test']);
		} else {
			$oMontest = $object;
		}
		// Maintenant on compare avec celle en session
		if (!empty($_SESSION['montest']) && sizeof($_SESSION['montest']->compareTo($oMontest)) > 0) {
			$_SESSION['montest'] = $oMontest;
		}
		if ($oMontest->getId() == 0) {
			//Go TO SAVE
			self::save($oMontest);
		} else {
			// on update car les objets sont different
			if (database::getInstance()->executeRequete($oMontest->update()) === true) {
				//maj id dans la liste
				self::$_aListeMontest[$oMontest->getId()] = $oMontest;
				return true;
			} else {
				return false;
			}
		}
	}

	public function save($object=array()) {
		//Generated by ManagerGenerator::generateSave() on 02/08/2017 14:24:29
		// Verification
		if (empty($object)) {
			throw new Exception(get_class($this).": la sauvegarde se fait sur un objet.", E_USER_ERROR);
		}
		// si ce n'est pas une instance de la classe, on la cree
		if (! $object instanceof Montest) {
			$oMontest = new Montest($object['id'],$object['nom'],$object['prenom'],$object['test']);
		} else {
			$oMontest = $object;
		}
		if ($oMontest->getId() > 0) {
			//Go TO UPDATE
			self::update($oMontest);
		} else {
			// Appel de la methode update de l'objet
			if (database::getInstance()->executeRequete($oMontest->save()) === true) {
				//maj id dans la liste
				self::$_aListeMontest[$oMontest->getId()] = $oMontest;
				return true;
			} else {
				return false;
			}
		}
	}

	public function findBy($champ,$data='') {
		//Generated by ManagerGenerator::generateFindBy() on 02/08/2017 14:24:29
		// creation d'un objet de base de la classe
		$object = new Montest();
		$resultat = array();
		for ($i = 0; $i < sizeof($this -> _aListeMontest); $i++) {
			$object = $this -> _aListeMontest[$i];
			if ($object -> {'_'.strtolower($champ)} == $data) {
				$resultat[] = $object;
			}
		}
		if (sizeof($resultat) > 0) {
			//existe
			return $resultat;
		} else {
			//n'existe pas
			return "Pas de Montest de ".strtolower($champ)." '".$data."'";
		}
	}

	public function getMontestVide() {
		//Generated by ManagerGenerator::generateGetObjetVide() on 02/08/2017 14:24:29
		return new Montest();
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Montest21]*/	/*[/TAG-Montest21]*/


}
?>