TRUNCATE TABLE listeTAblesChamps;
INSERT INTO listeTablesChamps (nomTable,nomChamp,nomUsuel) VALUES 
('aaa','tpe','vide'),
('aaa','sme','vide'),
('aaa','mme','vide'),
('aaa','e','vide'),
('aaa','bge','vide'),
('aaa','dec','vide'),
('aaa','flt','vide'),
('aaa','dbl','vide'),
('aaa','bool','vide'),
('aaa','eumer','vide'),
('alliance','id','Identifiant'),
('alliance','nom','Nom'),
('alliance','tag','Tag'),
('alliance','description','Description'),
('arene','titre','Titre'),
('arene','nb_joueur_min','Nombre de joueur minimum'),
('arene','nb_joueur_max','Nombre de joueur maximum'),
('arene','fantassins_min','Nombre de fantassins minimum'),
('arene','fantassins_max','Nombre de fantassins maximum'),
('arene','motorise_min','Nombre de motorises minimum'),
('arene','motorise_max','Nombre de motorises maximum'),
('arene','aerien_min','Nombre de aeriens minimum'),
('arene','aerien_max','Nombre de aeriens maximum'),
('arene_armee','id','Identifiant'),
('arene_armee','idjoueur','Identifiant du joueur'),
('arene_armee','nom','Nom'),
('arene_armee','soldat','Soldat'),
('arene_armee','tireur','Tireur'),
('arene_armee','sapeur','Sapeur'),
('arene_armee','lanceroquette','Lance-Roquette'),
('arene_armee','jeep','Jeep'),
('arene_armee','tank','Tank'),
('arene_armee','chasseur','Chasseur'),
('arene_armee','bombardier','Bombardier'),
('arene_classement','id','Identifiant'),
('arene_classement','idjoueur','Identifiant du joueur'),
('arene_classement','points','Points'),
('arene_classement','place_precedente','Place Pr&eacute;c&eacute;dente'),
('arene_joueur','id','Identifiant'),
('arene_joueur','idjoueur','Identifiant du joueur'),
('arene_joueur','heure_connexion','Heure de connexion'),
('arene_joueur','heure_der_con','Heure de connexion'),
('arene_map','id','Identifiant'),
('arene_map','image','Image'),
('arene_map','coord_x','Coordonn&eacutes;es en X'),
('arene_map','coord_y','Coordonn&eacutes;es en Y'),
('arene_map','idterrain','Identifiant du terrain'),
('arene_map','occupe','Occup&eacute;'),
('arene_news','id','Identifiant'),
('arene_news','idjoueur','Identifiant du joueur'),
('arene_news','titre','Titre'),
('arene_news','contenu','Contenu de l''article'),
('arene_news','dateheure','Date Heure de l''article'),
('arene_unites','id','Identifiant'),
('arene_unites','idjoueur','Identifiant du joueur'),
('arene_unites','idtype','Identifiant du type'),
('arene_unites','nombre','Nombre d''unit&eacute;s'),
('arene_unites','pos_x','Position en X'),
('arene_unites','pos_y','Position en Y'),
('arene_unites','image','Image'),
('arene_unites','dir_vision','Direction de la vision'),
('armeecomposition','id','Identifiant'),
('armeecomposition','idarmee','Identifiant de l''arm&eacute;e'),
('armeecomposition','idtroupe','Identifiant de la troupe'),
('armees','id','Identifiant'),
('armees','nom','Nom'),
('armees','description','Description'),
('armees','idmembre','vide'),
('armees','points','vide'),
('armees','date_creation','Date de cr&eacute;ation'),
('armees','date_modification','vide'),
('batiment','batimentId','vide'),
('batiment','batimentNom','vide'),
('batiment','batimentDesc','vide'),
('batiment','batimentVie','vide'),
('batiment','batimentDefense','vide'),
('batiment','batimentBouclier','vide'),
('batiment','production','vide'),
('boussole','id','Identifiant'),
('boussole','orientation','Orientation de la boussole'),
('camp','id','Identifiant'),
('camp','nom','Nom'),
('camp','description','Description'),
('camp','attaque','Bonus/Malus pour attaque'),
('camp','sauvegarde','Bonus/Malus pour sauvegarde'),
('camp','initiative','Bonus/Malus pour initiative'),
('camp','toucher','Bonus/Malus pour toucher'),
('carte','id','Identifiant'),
('carte','nom','Nom'),
('carte','iddimension','Identifaint de la dimention de la carte'),
('carte','apercu','Chemin vers l''apper&ccedil;u'),
('carte','edition','Carte en &eacute;dition O/N'),
('carteedit','id','Identifiant'),
('carteedit','nom','Nom'),
('carteedit','nb_cases_x','Nombre de case en X'),
('carteedit','nb_cases_y','Nombre de case en Y'),
('carteplateaux','id','Identifiant'),
('carteplateaux','idcarte','Identifiant de la carte affect&eacute;e'),
('carteplateaux','idplateau','Identifiant du plateau de la carte'),
('carteplateaux','nom','Nom'),
('carteplateaux','x','Coordonn&eacute;e X'),
('carteplateaux','y','Coordonn&eacute;e Y'),
('cases','id','Identifiant'),
('cases','idcarte','Identifiant de la carte de la case'),
('cases','x','Coordonn&eacute;e X'),
('cases','y','Coordonn&eacute;e Y'),
('cases','vision','Nombre de case vues &agrave; partir de la case'),
('cases','idunite','Identifiant de l''unit&eacute; sur la case'),
('cases','idunitejoueur','Identifiant de l''unit&eacute; du joueur sur la case'),
('cases','iddecor','Identifiant du d&eacute;cor de la case'),
('cases','etatCase','L''&eacute;tat de la case'),
('cases','bloque','Case bloqu&e&cute:e O/N'),
('categorie','id','Identifiant'),
('categorie','nom','Nom'),
('categorie','description','Description'),
('categorie','idtype','Identifiant du type'),
('chatcarte','idchat','Identifiant du chat'),
('chatcarte','idjoueur','Identifiant du joueur'),
('chatcarte','message','Le Message'),
('chatcarte','tspost','Timestamp du message'),
('chatcarte','idcarte','Identifiant de la carte'),
('commentaires','id','Identifiant'),
('commentaires','idnews','vide'),
('commentaires','idauteur','vide'),
('commentaires','contenu','vide'),
('commentaires','publication','vide'),
('commentaires','modification','vide'),
('commentaires','valide','vide'),
('connectes','id','Identifiant'),
('connectes','iduser','Identifiant du user'),
('connectes','date_connexion','Date de connexion'),
('decor','id','Identifiant'),
('decor','nom','Nom'),
('decor','description','Description'),
('decor','chemin','Chemin vers l''image'),
('decor','iddimension','Identifiant de la dimension associeacute;e'),
('decor','idcamp','Identifiant du camp'),
('decor','modificateur_vision','Si il mmodifie la vision d''une unit&eacute;'),
('decor','date_creation','Date de cr&eacute;ation'),
('decor','date_modification','Date de modification'),
('decor_utilise','id','Identifiant'),
('decor_utilise','nom','Nom du decor utilise'),
('decor_utilise','description','Description du decor utilise'),
('decor_utilise','chemin','Chemin vers l''image du decor utilise'),
('decor_utilise','modificateur_vision','vide'),
('decor_utilise','date_creation','Date de creation'),
('decor_utilise','date_modification','Date de modification'),
('decor_utilise','iddimension','Identifiant de la dimension'),
('decor_utilise','idcamp','Identifiant du Camp'),
('decor_utilise','iddecor','identifiant du d&eacute;cor'),
('decor_utilise','idcarte','Identifiant de la carte'),
('decor_utilise','idcase','Identifiant de la (ou des) case(s)'),
('decor_utilise','coordonnees','coordonnees du decor'),
('design','id','Identifiant'),
('design','nom','Nom'),
('design','description','Description'),
('design','chemin','chemin du design'),
('dimension','id','Identifiant'),
('dimension','nom','Nom'),
('dimension','idtype','Identifiant du type'),
('dimension','largeur','La largeur'),
('dimension','longueur','La longueur'),
('dimension','surface','La surface'),
('droit','id','Identifiant'),
('droit','nom','vide'),
('droit','valeur','vide'),
('droit_membre','iddroit','vide'),
('droit_membre','idjoueur','Identifiant du joueur'),
('equipement','id','Identifiant'),
('equipement','nom','Nom'),
('equipement','description','Description'),
('equipement','categorie','Identifiant de la cat&eacute;gorie affect&eacute;e'),
('equipement','cp','Courte Port&eacute;e'),
('equipement','lp','Longue Port&eacute;'),
('equipement','mtcp','Modificateur courte port&eacute;e'),
('equipement','mtlp','Modificateur longue port&eacute;e'),
('equipement','dommage','Dommages'),
('equipement','msvg','Modificateur de sauvegarde'),
('equipement','gab','Gabarit pour les armes de zone'),
('equipement','type','Type'),
('equipement','fo','Force'),
('equipement','sauvegarde','Sauvegarde'),
('equipement','mmvt','Modificateur de mouvement'),
('equipement','encombrement','Encombrement dans l''inventaire'),
('equipement','deux_mains','Deux mains n&eacute;cessaires'),
('equipement','cout','Co&ucirc;t'),
('equipement','date_creation','Date de cr&eacute;ation'),
('equipement','chemin','Chemin vers l''image'),
('equipement','tile','Identifiant de la case'),
('equipement_joueur','id','Identifiant'),
('equipement_joueur','idjoueur','Identifiant du joueur'),
('equipement_joueur','idunitejoueur','Identifiant de l''unit&eacute; du joueur portant l''&eacute;quipement'),
('equipement_joueur','nom','Nom'),
('equipement_joueur','description','Description'),
('equipement_joueur','idcategorie','Identifiant de la cat&eacute;gorie affect&eacute;e'),
('equipement_joueur','cp','Courte Port&eacute;e'),
('equipement_joueur','lp','Longue Port&eacute;'),
('equipement_joueur','mtcp','Modificateur courte port&eacute;e'),
('equipement_joueur','mtlp','Modificateur longue port&eacute;e'),
('equipement_joueur','dommage','Dommages'),
('equipement_joueur','msvg','Modificateur de sauvegarde'),
('equipement_joueur','gab','Gabarit pour les armes de zone'),
('equipement_joueur','ty','Type'),
('equipement_joueur','fo','Force'),
('equipement_joueur','sauvegarde','Sauvegarde'),
('equipement_joueur','mmvt','Modificateur de mouvement'),
('equipement_joueur','encombrement','Encombrement dans l''inventaire'),
('equipement_joueur','deux_mains','Deux mains n&eacute;cessaires'),
('equipement_joueur','cout','Co&ucirc;t'),
('equipement_joueur','date_creation','Date de cr&eacute;ation'),
('equipement_joueur','used','Utils&eacute; O/N'),
('equipement_joueur','chemin','Chemin vers l''image'),
('equipement_joueur','idcase','Identifiant de la case'),
('fantassins','fantassinId','vide'),
('fantassins','fantassinNom','vide'),
('fantassins','fantassinDesc','vide'),
('fantassins','fantassinType','vide'),
('fantassins','fantassinVie','vide'),
('fantassins','fantassinAttaque','vide'),
('fantassins','fantassinDefense','vide'),
('fantassins','fantassinMouvement','vide'),
('fifo','id','Identifiant'),
('fifo','idmembre','vide'),
('fifo','dateheure','vide'),
('fifo','nombre','vide'),
('fifo','idunite','vide'),
('fifo','idbatiment','vide'),
('gabarit','id','Identifiant'),
('gabarit','nom','Nom'),
('gabarit','x_depart','vide'),
('gabarit','y_depart','vide'),
('gabarit','x_arrivee','vide'),
('gabarit','y_arrivee','vide'),
('gabarit','taille','vide'),
('groupe','id','Identifiant'),
('groupe','nom','Nom'),
('groupe','valeur','vide'),
('hero','id','Identifiant'),
('hero','idmembre','vide'),
('hero','nom','Nom'),
('hero','description','Description'),
('hero','experience','vide'),
('hero','idcamp','Identifiant du camp'),
('hero','idunitejoueur','vide'),
('inventaire','id','Identifiant'),
('inventaire','idhero','vide'),
('inventaire','idequipement','vide'),
('joueur','joueurId','vide'),
('joueur','joueurPseudo','vide'),
('joueur','joueurPwd','vide'),
('joueur','joueurMail','vide'),
('joueur','privilegeId','vide'),
('joueur','joueurXPos','vide'),
('joueur','joueurYPos','vide'),
('joueur','idAlliance','vide'),
('joueur','joueurDateInscription','vide'),
('joueur','joueurDateDerniereConnexion','vide'),
('joueur','ressource1','vide'),
('joueur','production1','vide'),
('joueur','ressource2','vide'),
('joueur','production2','vide'),
('joueur','ressource3','vide'),
('joueur','production3','vide'),
('joueur','ressource1base','vide'),
('joueur','ressource2base','vide'),
('joueur','ressource3base','vide'),
('joueur','test','vide'),
('journal','id','Identifiant'),
('journal','idmembre1','vide'),
('journal','action','vide'),
('journal','idmembre2','vide'),
('journal','date_heure','vide'),
('listetableschamps','id','Identifiant'),
('listetableschamps','nomTable','vide'),
('listetableschamps','nomChamp','vide'),
('listetableschamps','nomUsuel','vide'),
('membre','id','Identifiant'),
('membre','pseudo','Le pseudo'),
('membre','password','Mot de passe crypt&eacute;'),
('membre','mail','Adresse mail'),
('membre','date_inscription','La date d''inscription'),
('membre','staff','Mebre du staff O/N'),
('membre','idgroupe','Identifiant du groupe'),
('membre','experience','Exp&eacute;rience'),
('membre','description','Description'),
('membre','cle_activation','La cl&eacute; d''activation'),
('membre','avatar','Avatar'),
('membre','iddesign','Identifiant du design choisit'),
('membre','points','Nombre de point'),
('module','id','Identifiant'),
('module','nom','Nom'),
('module','actif','Module Actif O/N'),
('news','id','Identifiant'),
('news','idauteur','Identifiant de l''auteur de l''article'),
('news','titre','Titre'),
('news','contenu','Contenu de l''article'),
('news','publication','Date de publication'),
('news','modification','Date de modification'),
('news','valide','vide'),
('oldcarte','id_carte','vide'),
('oldcarte','x','vide'),
('oldcarte','y','vide'),
('oldcarte','vision','vide'),
('oldcarte','terrain','vide'),
('permission','id','Identifiant'),
('permission','idprivilege','vide'),
('permission','idgroupe','vide'),
('plateau','id','Identifiant'),
('plateau','nom','nom du plateau'),
('plateau','description','description du plateau'),
('plateau','chemin','Chemin vers l''image'),
('plateau','nb_cases_x','Nombre de case en X'),
('plateau','nb_cases_y','Nombre de case en Y'),
('privilege','id','Identifiant'),
('privilege','nom','Nom'),
('privilege','description','Description'),
('privilege_groupe','idprivilege','vide'),
('privilege_groupe','idgroupe','vide'),
('sol','id','Identifiant'),
('sol','nom','Nom'),
('sol','nb_cases_x','Nombre de case en X'),
('sol','nb_cases_y','Nombre de case en Y'),
('sol','chemin','Chemin vers l''image du sol'),
('solscarteedit','id','Identifiant'),
('solscarteedit','idcarte','Identifiant de la carte'),
('solscarteedit','idsol','Identifiant du sol'),
('solscarteedit','x','Coordonn&eacute; X du coin haut gauche'),
('solscarteedit','y','Coordonn&eacute; Y du coin haut gauche'),
('statmembre','id','Identifiant'),
('statmembre','idmembre','vide'),
('statmembre','idhero','vide'),
('statmembre','tues','vide'),
('statmembre','morts','vide'),
('statmembre','victoires','vide'),
('statmembre','defaites','vide'),
('technologie','technologieId','vide'),
('technologie','technologieNom','vide'),
('technologie','technologieDesc','vide'),
('temp','id','Identifiant'),
('temp','pseudo','vide'),
('temp','password','vide'),
('temp','email','vide'),
('temp','adresse_ip','vide'),
('temp','date_inscription','vide'),
('temp','date_suppression','vide'),
('temp','checksum','vide'),
('temp_user','id','Identifiant'),
('temp_user','pseudo','vide'),
('temp_user','password','vide'),
('temp_user','mail','vide'),
('temp_user','checksum','vide'),
('temp_user','date_creation','Date de cr&eacute;ation'),
('temp_user','date_suppression','vide'),
('terrain','id','Identifiant'),
('terrain','nom','Nom'),
('terrain','description','Description'),
('terrain','image','chemin vers l''image du terrain'),
('test','id','Identifiant'),
('test','pseudo','vide'),
('test','mail','vide'),
('toto','id','Identifiant'),
('toto','nom','Nom'),
('toto','prenom','vide'),
('troupecomposition','id','Identifiant'),
('troupecomposition','idtroupe','Identifiant de la troupe'),
('troupecomposition','idunitejoueur','Identifiant de l''unit&eacute; du joueur'),
('troupecomposition','idhero','Identifiant du h&eacute;ros'),
('troupecomposition','heros','Est un h&eacute;ros ou non'),
('troupes','id','Identifiant'),
('troupes','nom','Nom'),
('troupes','description','Description'),
('troupes','idmembre','vide'),
('troupes','date_creation','Date de cr&eacute;ation'),
('troupes','date_modification','vide'),
('type','id','Identifiant'),
('type','nom','Nom'),
('type','description','Description'),
('unite','id','Identifiant'),
('unite','nom','Nom'),
('unite','description','Description'),
('unite','def_av','D&eacute;fense &agrave l''avant'),
('unite','def_ar','D&eacute;fense &agrave l''arri&egrave;re'),
('unite','def_g','D&eacute;fense c&ocirc;t&eacute; gauche'),
('unite','def_d','D&eacute;fense c&ocirc;t&eacute; droit'),
('unite','mouvement','Mouvement restant'),
('unite','capacite','Capacit&eacute;pour un v&eacute;hicule'),
('unite','pilote','Pilote pour un v&eacute;hicule'),
('unite','co_pilote','Co Pilote pour un v&eacute;hicule'),
('unite','experience','Exp&eacute;rience'),
('unite','att_g','Identifiant de l''arme de la main gauche'),
('unite','att_d','Identifiant de l''arme de la main droite'),
('unite','armure','Armure'),
('unite','coiffe','Coiffe (Armure)'),
('unite','etendart','&Eacute;tendard'),
('unite','toucher','Toucher'),
('unite','initiative','Initiative'),
('unite','sauvegarde','Sauvegarde'),
('unite','endurance','Endurance'),
('unite','cac','Corps &agrave; corps'),
('unite','fo','Force'),
('unite','attaque','Attaque'),
('unite','intell','Intelligence'),
('unite','ty','Type'),
('unite','idcamp','Identifiant du camp'),
('unite','cout','Co&ucirc;t'),
('unite','date_creation','Date de cr&eacute;ation'),
('unite','chemin','Chemin vers l''image'),
('unite','iddimension','Identifiant de la dimension de l''unit&eacute;'),
('unite','aAttaqueCeTour','vide'),
('unite','sEstDeplaceCeTour','vide'),
('unite','aChargeCeTour','vide'),
('unite','idcase','Identifiant de la case ou est l''unite'),
('unite_joueur','id','Identifiant'),
('unite_joueur','idjoueur','Identifiant du joueur'),
('unite_joueur','nom','Nom'),
('unite_joueur','description','Description'),
('unite_joueur','def_av','D&eacute;fence sur l''avant'),
('unite_joueur','def_ar','D&eacute;fence sur l''arri&egrave;re'),
('unite_joueur','def_g','D&eacute;fence c&ocirc;t&eacute; gauche'),
('unite_joueur','def_d','D&eacute;fence c&ocirc;t&eacute; droit'),
('unite_joueur','mouvement','Nmobre de mouvement restant'),
('unite_joueur','experience','Exp&eacute;rience de l''unit&eacute;'),
('unite_joueur','att_g','Identifiant de l''arme main gauche'),
('unite_joueur','att_d','Identifiant de l''arme main droite'),
('unite_joueur','armure','Armure'),
('unite_joueur','coiffe','Coiffe (armure)'),
('unite_joueur','etendart','&Eacute;tendart'),
('unite_joueur','toucher','Toucher'),
('unite_joueur','initiative','Initiative'),
('unite_joueur','sauvegarde','Sauvegarde'),
('unite_joueur','endurance','Endurance'),
('unite_joueur','cac','Corps &agrave; corps'),
('unite_joueur','fo','Force'),
('unite_joueur','attaque','Attaque'),
('unite_joueur','intell','Intelligence'),
('unite_joueur','ty','Type'),
('unite_joueur','capacite','Capacit&eacute; de transport pour un v&eacute;hicule'),
('unite_joueur','pilote','Pilote pour un v&eacute;hicule'),
('unite_joueur','co_pilote','Co Pilote pour un v&eacute;hicule'),
('unite_joueur','cout','Co&ucirc;t de l''unit&eacute;'),
('unite_joueur','date_creation','Date de cr&eacute;ation'),
('unite_joueur','idcase','Identifiant de la case'),
('unite_joueur','idcamp','Identifiant du camp'),
('unite_joueur','idarmee','Identifiant de l''arm&eacute;e'),
('unite_joueur','chemin','Chemin vers l''image'),
('unite_joueur','iddimension','Identifiant de la dimension de l''unit&eacute;'),
('unite_joueur','aAttaqueCeTour','vide'),
('unite_joueur','sEstDeplaceCeTour','vide'),
('unite_joueur','aChargeCeTour','vide'),
('unite_type','id','Identifiant'),
('unite_type','nom','Nom'),
('vehicule','vehiculeId','vide'),
('vehicule','vehiculeNom','vide'),
('vehicule','vehiculeDesc','vide'),
('vehicule','vehiculeType','vide'),
('vehicule','vehiculeVie','vide'),
('vehicule','vehiculeAttaque','vide'),
('vehicule','vehiculeDefense','vide'),
('vehicule','vehiculeDeplacement','vide');