<?php
	/*
	 * AUTO-GENERATED FILE on 23/02/2017 14:20:59 BY FactoryGenerator.class.php
	 */

abstract class FactoryTechnologie {

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Technologie11]*/	/*[/TAG-Technologie11]*/


	public static function getFromTableTechnologie($id=-1) {
		//Generated by FactoryGenerator::generateGetAllFromTable()
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `technologie`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > -1) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > -1) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table technologie');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Technologie2]*/	/*[/TAG-Technologie2]*/

		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Technologie($data['technologieId'],$data['technologieNom'],$data['technologieDesc']);
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-getFromTableTechnologie1]*/	/*[/TAG-getFromTableTechnologie1]*/

		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableTechnologieId($technologieid=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `technologie` ';
		if ($technologieid == 0) {
			$requete .= 'WHERE technologieid > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE technologieid = :technologieid ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$technologieid = array(':technologieid' => $technologieid);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($technologieid) || $technologieid > 0) {
			database::getInstance() -> bind($technologieid);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table technologie');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Technologie($data['technologieId'],$data['technologieNom'],$data['technologieDesc']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableTechnologieNom($technologienom=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `technologie` ';
		if ($technologienom == 0) {
			$requete .= 'WHERE technologienom > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE technologienom = :technologienom ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$technologienom = array(':technologienom' => $technologienom);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($technologienom) || $technologienom > 0) {
			database::getInstance() -> bind($technologienom);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table technologie');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Technologie($data['technologieId'],$data['technologieNom'],$data['technologieDesc']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableTechnologieDesc($technologiedesc=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `technologie` ';
		if ($technologiedesc == 0) {
			$requete .= 'WHERE technologiedesc > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE technologiedesc = :technologiedesc ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$technologiedesc = array(':technologiedesc' => $technologiedesc);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($technologiedesc) || $technologiedesc > 0) {
			database::getInstance() -> bind($technologiedesc);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table technologie');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Technologie($data['technologieId'],$data['technologieNom'],$data['technologieDesc']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Technologie21]*/	/*[/TAG-Technologie21]*/


}
?>