<?php
	/*
	 * AUTO-GENERATED FILE on 23/02/2017 14:20:58 BY FactoryGenerator.class.php
	 */

abstract class FactoryJournal {

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Journal11]*/	/*[/TAG-Journal11]*/


	public static function getFromTableJournal($id=-1) {
		//Generated by FactoryGenerator::generateGetAllFromTable()
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `journal`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > -1) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > -1) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table journal');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Journal2]*/	/*[/TAG-Journal2]*/

		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Journal($data['id'],$data['idmembre1'],$data['action'],$data['idmembre2'],$data['date_heure']);
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-getFromTableJournal1]*/	/*[/TAG-getFromTableJournal1]*/

		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableIdmembre1($idmembre1=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `journal` ';
		if ($idmembre1 == 0) {
			$requete .= 'WHERE idmembre1 > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE idmembre1 = :idmembre1 ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$idmembre1 = array(':idmembre1' => $idmembre1);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($idmembre1) || $idmembre1 > 0) {
			database::getInstance() -> bind($idmembre1);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table journal');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Journal($data['id'],$data['idmembre1'],$data['action'],$data['idmembre2'],$data['date_heure']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableIdmembre2($idmembre2=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `journal` ';
		if ($idmembre2 == 0) {
			$requete .= 'WHERE idmembre2 > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE idmembre2 = :idmembre2 ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$idmembre2 = array(':idmembre2' => $idmembre2);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($idmembre2) || $idmembre2 > 0) {
			database::getInstance() -> bind($idmembre2);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table journal');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Journal($data['id'],$data['idmembre1'],$data['action'],$data['idmembre2'],$data['date_heure']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Journal21]*/	/*[/TAG-Journal21]*/


}
?>