<?php
	/*
	 * AUTO-GENERATED FILE on 12/05/2017 15:42:37 BY FactoryGenerator.class.php
	 */

abstract class FactoryPartie {

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Partie11]*/	/*[/TAG-Partie11]*/


	public static function getFromTablePartie($id=-1) {
		//Generated by FactoryGenerator::generateGetAllFromTable() on 12/05/2017 15:42:37
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `partie`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > -1) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > -1) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table partie');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Partie2]*/	/*[/TAG-Partie2]*/

		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Partie($data['id'],$data['nom'],$data['carte'],$data['date_creation'],$data['date_fin'],$data['ia']);
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-getFromTablePartie1]*/	/*[/TAG-getFromTablePartie1]*/

		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableCarte($carte=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 12/05/2017 15:42:37
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `partie` ';
		if ($carte == 0) {
			$requete .= 'WHERE carte > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE carte = :carte ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$carte = array(':carte' => $carte);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($carte) || $carte > 0) {
			database::getInstance() -> bind($carte);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table partie');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Partie($data['id'],$data['nom'],$data['carte'],$data['date_creation'],$data['date_fin'],$data['ia']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Partie21]*/	/*[/TAG-Partie21]*/


}
?>