<?php
	/*
	 * AUTO-GENERATED FILE on 23/02/2017 14:20:59 BY FactoryGenerator.class.php
	 */

abstract class FactoryTroupecomposition {

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Troupecomposition11]*/	/*[/TAG-Troupecomposition11]*/


	public static function getFromTableTroupecomposition($id=-1) {
		//Generated by FactoryGenerator::generateGetAllFromTable()
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `troupecomposition`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > -1) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > -1) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table troupecomposition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Troupecomposition2]*/	/*[/TAG-Troupecomposition2]*/

		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Troupecomposition($data['id'],$data['troupe'],$data['unite_joueur'],$data['hero'],$data['heros']);
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-getFromTableTroupecomposition1]*/	/*[/TAG-getFromTableTroupecomposition1]*/

		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableTroupe($troupe=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `troupecomposition` ';
		if ($troupe == 0) {
			$requete .= 'WHERE troupe > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE troupe = :troupe ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$troupe = array(':troupe' => $troupe);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($troupe) || $troupe > 0) {
			database::getInstance() -> bind($troupe);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table troupecomposition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Troupecomposition($data['id'],$data['troupe'],$data['unite_joueur'],$data['hero'],$data['heros']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableUnite_joueur($unite_joueur=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `troupecomposition` ';
		if ($unite_joueur == 0) {
			$requete .= 'WHERE unite_joueur > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE unite_joueur = :unite_joueur ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$unite_joueur = array(':unite_joueur' => $unite_joueur);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($unite_joueur) || $unite_joueur > 0) {
			database::getInstance() -> bind($unite_joueur);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table troupecomposition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Troupecomposition($data['id'],$data['troupe'],$data['unite_joueur'],$data['hero'],$data['heros']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableHero($hero=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `troupecomposition` ';
		if ($hero == 0) {
			$requete .= 'WHERE hero > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE hero = :hero ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$hero = array(':hero' => $hero);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($hero) || $hero > 0) {
			database::getInstance() -> bind($hero);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table troupecomposition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Troupecomposition($data['id'],$data['troupe'],$data['unite_joueur'],$data['hero'],$data['heros']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableHeros($heros=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `troupecomposition` ';
		if ($heros == 0) {
			$requete .= 'WHERE heros > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE heros = :heros ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$heros = array(':heros' => $heros);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($heros) || $heros > 0) {
			database::getInstance() -> bind($heros);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table troupecomposition');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Troupecomposition($data['id'],$data['troupe'],$data['unite_joueur'],$data['hero'],$data['heros']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Troupecomposition21]*/	/*[/TAG-Troupecomposition21]*/


}
?>