<?php
	/*
	 * AUTO-GENERATED FILE on 23/02/2017 14:20:58 BY FactoryGenerator.class.php
	 */

abstract class FactoryFantassins {

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Fantassins11]*/	/*[/TAG-Fantassins11]*/


	public static function getFromTableFantassins($id=-1) {
		//Generated by FactoryGenerator::generateGetAllFromTable()
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `fantassins`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > -1) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > -1) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table fantassins');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Fantassins2]*/	/*[/TAG-Fantassins2]*/

		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Fantassins($data['fantassinId'],$data['fantassinNom'],$data['fantassinDesc'],$data['fantassinType'],$data['fantassinVie'],$data['fantassinAttaque'],$data['fantassinDefense'],$data['fantassinMouvement']);
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-getFromTableFantassins1]*/	/*[/TAG-getFromTableFantassins1]*/

		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableFantassinType($fantassintype=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK()
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `fantassins` ';
		if ($fantassintype == 0) {
			$requete .= 'WHERE fantassintype > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE fantassintype = :fantassintype ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$fantassintype = array(':fantassintype' => $fantassintype);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($fantassintype) || $fantassintype > 0) {
			database::getInstance() -> bind($fantassintype);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table fantassins');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Fantassins($data['fantassinId'],$data['fantassinNom'],$data['fantassinDesc'],$data['fantassinType'],$data['fantassinVie'],$data['fantassinAttaque'],$data['fantassinDefense'],$data['fantassinMouvement']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Fantassins21]*/	/*[/TAG-Fantassins21]*/


}
?>