<?php
	/*
	 * AUTO-GENERATED FILE on 03/10/2017 14:32:14 BY FactoryGenerator.class.php
	 */

abstract class FactoryUnite {

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Unite11]*/	/*[/TAG-Unite11]*/


	public static function getFromTableUnite($id=-1) {
		//Generated by FactoryGenerator::generateGetAllFromTable() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `unite`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > -1) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > -1) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Unite2]*/	/*[/TAG-Unite2]*/

		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-getFromTableUnite1]*/	/*[/TAG-getFromTableUnite1]*/

		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableEquipementarmegauche($equipementarmegauche=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($equipementarmegauche == 0) {
			$requete .= 'WHERE equipementarmegauche > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE equipementarmegauche = :equipementarmegauche ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$equipementarmegauche = array(':equipementarmegauche' => $equipementarmegauche);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($equipementarmegauche) || $equipementarmegauche > 0) {
			database::getInstance() -> bind($equipementarmegauche);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableEquipementarmedroite($equipementarmedroite=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($equipementarmedroite == 0) {
			$requete .= 'WHERE equipementarmedroite > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE equipementarmedroite = :equipementarmedroite ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$equipementarmedroite = array(':equipementarmedroite' => $equipementarmedroite);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($equipementarmedroite) || $equipementarmedroite > 0) {
			database::getInstance() -> bind($equipementarmedroite);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableEquipementarmure($equipementarmure=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($equipementarmure == 0) {
			$requete .= 'WHERE equipementarmure > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE equipementarmure = :equipementarmure ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$equipementarmure = array(':equipementarmure' => $equipementarmure);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($equipementarmure) || $equipementarmure > 0) {
			database::getInstance() -> bind($equipementarmure);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableEquipementcoiffe($equipementcoiffe=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($equipementcoiffe == 0) {
			$requete .= 'WHERE equipementcoiffe > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE equipementcoiffe = :equipementcoiffe ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$equipementcoiffe = array(':equipementcoiffe' => $equipementcoiffe);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($equipementcoiffe) || $equipementcoiffe > 0) {
			database::getInstance() -> bind($equipementcoiffe);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableEquipementetendart($equipementetendart=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($equipementetendart == 0) {
			$requete .= 'WHERE equipementetendart > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE equipementetendart = :equipementetendart ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$equipementetendart = array(':equipementetendart' => $equipementetendart);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($equipementetendart) || $equipementetendart > 0) {
			database::getInstance() -> bind($equipementetendart);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableCamp($camp=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($camp == 0) {
			$requete .= 'WHERE camp > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE camp = :camp ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$camp = array(':camp' => $camp);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($camp) || $camp > 0) {
			database::getInstance() -> bind($camp);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableDimension($dimension=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($dimension == 0) {
			$requete .= 'WHERE dimension > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE dimension = :dimension ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$dimension = array(':dimension' => $dimension);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($dimension) || $dimension > 0) {
			database::getInstance() -> bind($dimension);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableTile($tile=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 03/10/2017 14:32:14
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `unite` ';
		if ($tile == 0) {
			$requete .= 'WHERE tile > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE tile = :tile ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$tile = array(':tile' => $tile);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($tile) || $tile > 0) {
			database::getInstance() -> bind($tile);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Unite21]*/
	public static function getPlayableUnitsForIA($idCarte=-1) {
	    $listeObjet = array();
	    $requete = 'SELECT * FROM `unite` ';
	    $requete .= ' where tile in (select id from tile where carte = :carte) ';
	    $requete .= 'having (aattaquecetour+sestdeplacecetour) < 2 ';
	    $requete .= ' ORDER BY id ASC';
	    database::getInstance() -> prepareRequete($requete);
	    database::getInstance() -> bind(array(':carte' => $idCarte));
	    if (! database::getInstance() -> executeRequete()) {
	        throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table unite');
	    }
	    // Recuperation des donnees
	    $datas = database::getInstance() -> getTableauResultat();
	    // Traitement des donnees
	    foreach ($datas AS $data) {
	        $listeObjet[] = new Unite($data['id'],$data['nom'],$data['description'],$data['def_av'],$data['def_ar'],$data['def_g'],$data['def_d'],$data['mouvement'],$data['capacite'],$data['pilote'],$data['co_pilote'],$data['experience'],$data['equipementarmegauche'],$data['equipementarmedroite'],$data['equipementarmure'],$data['equipementcoiffe'],$data['equipementetendart'],$data['toucher'],$data['initiative'],$data['sauvegarde'],$data['endurance'],$data['cac'],$data['fo'],$data['attaque'],$data['intell'],$data['ty'],$data['camp'],$data['cout'],$data['date_creation'],$data['chemin'],$data['dimension'],$data['aattaquecetour'],$data['sestdeplacecetour'],$data['achargecetour'],$data['tile'],$data['pdv'],$data['ingame']);
	    }
	    if (sizeof($listeObjet) == 1) {
	        $listeObjet = $listeObjet[0];
	    }
	    return $listeObjet;
	}
	
	/*[/TAG-Unite21]*/


}
?>