<?php
	/*
	 * AUTO-GENERATED FILE on 02/08/2017 14:24:29 BY FactoryGenerator.class.php
	 */

abstract class FactoryMontest {

	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Montest11]*/	/*[/TAG-Montest11]*/


	public static function getFromTableMontest($id=-1) {
		//Generated by FactoryGenerator::generateGetAllFromTable() on 02/08/2017 14:24:29
		$listeObjet = array();
		// Lancement de la requete
		if (empty(self::$_requete)) {
			$requete = 'SELECT * FROM `montest`';
		} else {
			$requete = self::$_requete;
		}
		if (!is_array($id)) {
			if ($id > -1) {
				$requete .= ' WHERE id = :id';
				//Il faut que le parametre soit dans un array pour le BIND
				$id = array(':id' => $id);
			} else {
				/* Tous les objets ==> il faut les ordonner */
				$requete .= ' ORDER BY id ASC';
			}
		} else {
			$requete .= ' WHERE id IN ('.implode(",",$id).') ORDER BY id ASC';
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($id) || $id > -1) {
			database::getInstance() -> bind($id);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table montest');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Montest2]*/	/*[/TAG-Montest2]*/

		/* Traitement des donnees */
		foreach ($datas AS $data) {
			/* objet par defaut */
			$listeObjet[] = new Montest($data['id'],$data['nom'],$data['prenom'],$data['test']);
		
	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-getFromTableMontest1]*/	/*[/TAG-getFromTableMontest1]*/

		}
		if (!empty($listeObjet) && sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}

	public static function getFromExtTableTest($test=0) {
		//Generated by FactoryGenerator::generateGetFromTableFromFK() on 02/08/2017 14:24:29
		$listeObjet = array();
		// Lancement de la requete
		$requete = 'SELECT * FROM `montest` ';
		if ($test == 0) {
			$requete .= 'WHERE test > 0 ORDER BY id ASC';
		} else {
			$requete .= 'WHERE test = :test ORDER BY id ASC';
			//Il faut que le parametre soit dans un array pour le BIND
			$test = array(':test' => $test);
		}
		database::getInstance() -> prepareRequete($requete);
		if (is_array($test) || $test > 0) {
			database::getInstance() -> bind($test);
		}
		if (! database::getInstance() -> executeRequete()) {
			throw new Exception(__CLASS__.'::'.__FUNCTION__.'(): Impossible de lire la table montest');
		}
		// Recuperation des donnees
		$datas = database::getInstance() -> getTableauResultat();
		// Traitement des donnees
		foreach ($datas AS $data) {
			$listeObjet[] = new Montest($data['id'],$data['nom'],$data['prenom'],$data['test']);
		}
		if (sizeof($listeObjet) == 1) {
			$listeObjet = $listeObjet[0];
		}
		return $listeObjet;
	}


	/*
	 * Entre ces deux balises vous pourrez mettre votre code specifique a la classe.
	 * Il sera preserve lors de la reconstruction automatique.
	 */
	/*[TAG-Montest21]*/	/*[/TAG-Montest21]*/


}
?>